! Stub file to create library for Intel Fortran 32 Bit procedure wrapper generated by apiwrapper for GAMS Version 24.0.2

LOGICAL FUNCTION XCreate_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: xcreate_
  !DEC$ ATTRIBUTES STDCALL :: xcreate_
  !DEC$ ATTRIBUTES ALIAS: 'xcreate_'::xcreate_
  INTEGER(KIND=4) :: pgdx
END FUNCTION

LOGICAL FUNCTION XFree_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: xfree_
  !DEC$ ATTRIBUTES STDCALL :: xfree_
  !DEC$ ATTRIBUTES ALIAS: 'xfree_'::xfree_
  INTEGER(KIND=4) :: pgdx
END FUNCTION


INTEGER(KIND=4) FUNCTION gdxAcronymAdd_(pgdx,AName,Txt,AIndx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymadd_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymadd_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymadd_'::gdxacronymadd_
  INTEGER :: pgdx
  INTEGER :: AName
  INTEGER :: Txt
  INTEGER :: AIndx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymCount_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymcount_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymcount_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymcount_'::gdxacronymcount_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymGetInfo_(pgdx,N,AName,Txt,AIndx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymgetinfo_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymgetinfo_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymgetinfo_'::gdxacronymgetinfo_
  INTEGER :: pgdx
  INTEGER :: N
  INTEGER :: AName
  INTEGER :: Txt
  INTEGER :: AIndx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymGetMapping_(pgdx,N,orgIndx,newIndx, &
         autoIndex)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymgetmapping_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymgetmapping_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymgetmapping_'::gdxacronymgetmapping_
  INTEGER :: pgdx
  INTEGER :: N
  INTEGER :: orgIndx
  INTEGER :: newIndx
  INTEGER :: autoIndex
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymIndex_(pgdx,V,d_V)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymindex_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymindex_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymindex_'::gdxacronymindex_
  INTEGER :: pgdx
  INTEGER :: V
  INTEGER :: d_V
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymName_(pgdx,V,d_V,AName)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymname_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymname_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymname_'::gdxacronymname_
  INTEGER :: pgdx
  INTEGER :: V
  INTEGER :: d_V
  INTEGER :: AName
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymNextNr_(pgdx,NV)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymnextnr_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymnextnr_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymnextnr_'::gdxacronymnextnr_
  INTEGER :: pgdx
  INTEGER :: NV
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymSetInfo_(pgdx,N,AName,Txt,AIndx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymsetinfo_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymsetinfo_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymsetinfo_'::gdxacronymsetinfo_
  INTEGER :: pgdx
  INTEGER :: N
  INTEGER :: AName
  INTEGER :: Txt
  INTEGER :: AIndx
END FUNCTION

REAL(KIND=8) FUNCTION gdxAcronymValue_(pgdx,AIndx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxacronymvalue_
  !DEC$ ATTRIBUTES STDCALL :: gdxacronymvalue_
  !DEC$ ATTRIBUTES ALIAS : 'gdxacronymvalue_'::gdxacronymvalue_
  INTEGER :: pgdx
  INTEGER :: AIndx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAddAlias_(pgdx,Id1,Id2)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxaddalias_
  !DEC$ ATTRIBUTES STDCALL :: gdxaddalias_
  !DEC$ ATTRIBUTES ALIAS : 'gdxaddalias_'::gdxaddalias_
  INTEGER :: pgdx
  INTEGER :: Id1
  INTEGER :: Id2
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAddSetText_(pgdx,Txt,TxtNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxaddsettext_
  !DEC$ ATTRIBUTES STDCALL :: gdxaddsettext_
  !DEC$ ATTRIBUTES ALIAS : 'gdxaddsettext_'::gdxaddsettext_
  INTEGER :: pgdx
  INTEGER :: Txt
  INTEGER :: TxtNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAutoConvert_(pgdx,NV)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxautoconvert_
  !DEC$ ATTRIBUTES STDCALL :: gdxautoconvert_
  !DEC$ ATTRIBUTES ALIAS : 'gdxautoconvert_'::gdxautoconvert_
  INTEGER :: pgdx
  INTEGER :: NV
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxClose_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxclose_
  !DEC$ ATTRIBUTES STDCALL :: gdxclose_
  !DEC$ ATTRIBUTES ALIAS : 'gdxclose_'::gdxclose_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataErrorCount_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdataerrorcount_
  !DEC$ ATTRIBUTES STDCALL :: gdxdataerrorcount_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdataerrorcount_'::gdxdataerrorcount_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataErrorRecord_(pgdx,RecNr,KeyInt,Values)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdataerrorrecord_
  !DEC$ ATTRIBUTES STDCALL :: gdxdataerrorrecord_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdataerrorrecord_'::gdxdataerrorrecord_
  INTEGER :: pgdx
  INTEGER :: RecNr
  INTEGER :: KeyInt
  INTEGER :: Values
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadDone_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareaddone_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareaddone_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareaddone_'::gdxdatareaddone_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadFilteredStart_(pgdx,SyNr,FilterAction, &
         NrRecs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadfilteredstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadfilteredstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadfilteredstart_'::gdxdatareadfilteredstart_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: FilterAction
  INTEGER :: NrRecs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadMap_(pgdx,RecNr,KeyInt,Values, &
         DimFrst)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadmap_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadmap_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadmap_'::gdxdatareadmap_
  INTEGER :: pgdx
  INTEGER :: RecNr
  INTEGER :: KeyInt
  INTEGER :: Values
  INTEGER :: DimFrst
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadMapStart_(pgdx,SyNr,NrRecs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadmapstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadmapstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadmapstart_'::gdxdatareadmapstart_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: NrRecs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadRaw_(pgdx,KeyInt,Values,DimFrst)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadraw_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadraw_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadraw_'::gdxdatareadraw_
  INTEGER :: pgdx
  INTEGER :: KeyInt
  INTEGER :: Values
  INTEGER :: DimFrst
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadRawFast_(pgdx,SyNr,DP,NrRecs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadrawfast_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadrawfast_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadrawfast_'::gdxdatareadrawfast_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: DP
  INTEGER :: NrRecs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadRawStart_(pgdx,SyNr,NrRecs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadrawstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadrawstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadrawstart_'::gdxdatareadrawstart_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: NrRecs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadSlice_(pgdx,UelFilterStr,Dimen, &
         DP)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadslice_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadslice_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadslice_'::gdxdatareadslice_
  INTEGER :: pgdx
  INTEGER :: UelFilterStr
  INTEGER :: Dimen
  INTEGER :: DP
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadSliceStart_(pgdx,SyNr,ElemCounts)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadslicestart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadslicestart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadslicestart_'::gdxdatareadslicestart_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: ElemCounts
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadStr_(pgdx,KeyStr,Values,DimFrst)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadstr_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadstr_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadstr_'::gdxdatareadstr_
  INTEGER :: pgdx
  INTEGER :: KeyStr
  INTEGER :: Values
  INTEGER :: DimFrst
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadStrStart_(pgdx,SyNr,NrRecs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatareadstrstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatareadstrstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatareadstrstart_'::gdxdatareadstrstart_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: NrRecs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataSliceUELS_(pgdx,SliceKeyInt,KeyStr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatasliceuels_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatasliceuels_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatasliceuels_'::gdxdatasliceuels_
  INTEGER :: pgdx
  INTEGER :: SliceKeyInt
  INTEGER :: KeyStr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteDone_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatawritedone_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatawritedone_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatawritedone_'::gdxdatawritedone_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteMap_(pgdx,KeyInt,Values)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatawritemap_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatawritemap_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatawritemap_'::gdxdatawritemap_
  INTEGER :: pgdx
  INTEGER :: KeyInt
  INTEGER :: Values
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteMapStart_(pgdx,SyId,ExplTxt, &
         Dimen,Typ,UserInfo)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatawritemapstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatawritemapstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatawritemapstart_'::gdxdatawritemapstart_
  INTEGER :: pgdx
  INTEGER :: SyId
  INTEGER :: ExplTxt
  INTEGER :: Dimen
  INTEGER :: Typ
  INTEGER :: UserInfo
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteRaw_(pgdx,KeyInt,Values)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatawriteraw_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatawriteraw_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatawriteraw_'::gdxdatawriteraw_
  INTEGER :: pgdx
  INTEGER :: KeyInt
  INTEGER :: Values
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteRawStart_(pgdx,SyId,ExplTxt, &
         Dimen,Typ,UserInfo)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatawriterawstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatawriterawstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatawriterawstart_'::gdxdatawriterawstart_
  INTEGER :: pgdx
  INTEGER :: SyId
  INTEGER :: ExplTxt
  INTEGER :: Dimen
  INTEGER :: Typ
  INTEGER :: UserInfo
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteStr_(pgdx,KeyStr,Values)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatawritestr_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatawritestr_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatawritestr_'::gdxdatawritestr_
  INTEGER :: pgdx
  INTEGER :: KeyStr
  INTEGER :: Values
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteStrStart_(pgdx,SyId,ExplTxt, &
         Dimen,Typ,UserInfo)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxdatawritestrstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxdatawritestrstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxdatawritestrstart_'::gdxdatawritestrstart_
  INTEGER :: pgdx
  INTEGER :: SyId
  INTEGER :: ExplTxt
  INTEGER :: Dimen
  INTEGER :: Typ
  INTEGER :: UserInfo
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetDLLVersion_(pgdx,V)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxgetdllversion_
  !DEC$ ATTRIBUTES STDCALL :: gdxgetdllversion_
  !DEC$ ATTRIBUTES ALIAS : 'gdxgetdllversion_'::gdxgetdllversion_
  INTEGER :: pgdx
  INTEGER :: V
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxErrorCount_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxerrorcount_
  !DEC$ ATTRIBUTES STDCALL :: gdxerrorcount_
  !DEC$ ATTRIBUTES ALIAS : 'gdxerrorcount_'::gdxerrorcount_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxErrorStr_(pgdx,ErrNr,ErrMsg)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxerrorstr_
  !DEC$ ATTRIBUTES STDCALL :: gdxerrorstr_
  !DEC$ ATTRIBUTES ALIAS : 'gdxerrorstr_'::gdxerrorstr_
  INTEGER :: pgdx
  INTEGER :: ErrNr
  INTEGER :: ErrMsg
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFileInfo_(pgdx,FileVer,ComprLev)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxfileinfo_
  !DEC$ ATTRIBUTES STDCALL :: gdxfileinfo_
  !DEC$ ATTRIBUTES ALIAS : 'gdxfileinfo_'::gdxfileinfo_
  INTEGER :: pgdx
  INTEGER :: FileVer
  INTEGER :: ComprLev
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFileVersion_(pgdx,FileStr,ProduceStr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxfileversion_
  !DEC$ ATTRIBUTES STDCALL :: gdxfileversion_
  !DEC$ ATTRIBUTES ALIAS : 'gdxfileversion_'::gdxfileversion_
  INTEGER :: pgdx
  INTEGER :: FileStr
  INTEGER :: ProduceStr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterExists_(pgdx,FilterNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxfilterexists_
  !DEC$ ATTRIBUTES STDCALL :: gdxfilterexists_
  !DEC$ ATTRIBUTES ALIAS : 'gdxfilterexists_'::gdxfilterexists_
  INTEGER :: pgdx
  INTEGER :: FilterNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterRegister_(pgdx,UelMap)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxfilterregister_
  !DEC$ ATTRIBUTES STDCALL :: gdxfilterregister_
  !DEC$ ATTRIBUTES ALIAS : 'gdxfilterregister_'::gdxfilterregister_
  INTEGER :: pgdx
  INTEGER :: UelMap
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterRegisterDone_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxfilterregisterdone_
  !DEC$ ATTRIBUTES STDCALL :: gdxfilterregisterdone_
  !DEC$ ATTRIBUTES ALIAS : 'gdxfilterregisterdone_'::gdxfilterregisterdone_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterRegisterStart_(pgdx,FilterNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxfilterregisterstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxfilterregisterstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxfilterregisterstart_'::gdxfilterregisterstart_
  INTEGER :: pgdx
  INTEGER :: FilterNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFindSymbol_(pgdx,SyId,SyNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxfindsymbol_
  !DEC$ ATTRIBUTES STDCALL :: gdxfindsymbol_
  !DEC$ ATTRIBUTES ALIAS : 'gdxfindsymbol_'::gdxfindsymbol_
  INTEGER :: pgdx
  INTEGER :: SyId
  INTEGER :: SyNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetElemText_(pgdx,TxtNr,Txt,Node)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxgetelemtext_
  !DEC$ ATTRIBUTES STDCALL :: gdxgetelemtext_
  !DEC$ ATTRIBUTES ALIAS : 'gdxgetelemtext_'::gdxgetelemtext_
  INTEGER :: pgdx
  INTEGER :: TxtNr
  INTEGER :: Txt
  INTEGER :: Node
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetLastError_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxgetlasterror_
  !DEC$ ATTRIBUTES STDCALL :: gdxgetlasterror_
  !DEC$ ATTRIBUTES ALIAS : 'gdxgetlasterror_'::gdxgetlasterror_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=8) FUNCTION gdxGetMemoryUsed_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxgetmemoryused_
  !DEC$ ATTRIBUTES STDCALL :: gdxgetmemoryused_
  !DEC$ ATTRIBUTES ALIAS : 'gdxgetmemoryused_'::gdxgetmemoryused_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetSpecialValues_(pgdx,AVals)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxgetspecialvalues_
  !DEC$ ATTRIBUTES STDCALL :: gdxgetspecialvalues_
  !DEC$ ATTRIBUTES ALIAS : 'gdxgetspecialvalues_'::gdxgetspecialvalues_
  INTEGER :: pgdx
  INTEGER :: AVals
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetUEL_(pgdx,UelNr,Uel)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxgetuel_
  !DEC$ ATTRIBUTES STDCALL :: gdxgetuel_
  !DEC$ ATTRIBUTES ALIAS : 'gdxgetuel_'::gdxgetuel_
  INTEGER :: pgdx
  INTEGER :: UelNr
  INTEGER :: Uel
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxMapValue_(pgdx,D,d_D,sv)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxmapvalue_
  !DEC$ ATTRIBUTES STDCALL :: gdxmapvalue_
  !DEC$ ATTRIBUTES ALIAS : 'gdxmapvalue_'::gdxmapvalue_
  INTEGER :: pgdx
  INTEGER :: D
  INTEGER :: d_D
  INTEGER :: sv
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenAppend_(pgdx,FileName,Producer,ErrNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxopenappend_
  !DEC$ ATTRIBUTES STDCALL :: gdxopenappend_
  !DEC$ ATTRIBUTES ALIAS : 'gdxopenappend_'::gdxopenappend_
  INTEGER :: pgdx
  INTEGER :: FileName
  INTEGER :: Producer
  INTEGER :: ErrNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenRead_(pgdx,FileName,ErrNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxopenread_
  !DEC$ ATTRIBUTES STDCALL :: gdxopenread_
  !DEC$ ATTRIBUTES ALIAS : 'gdxopenread_'::gdxopenread_
  INTEGER :: pgdx
  INTEGER :: FileName
  INTEGER :: ErrNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenWrite_(pgdx,FileName,Producer,ErrNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxopenwrite_
  !DEC$ ATTRIBUTES STDCALL :: gdxopenwrite_
  !DEC$ ATTRIBUTES ALIAS : 'gdxopenwrite_'::gdxopenwrite_
  INTEGER :: pgdx
  INTEGER :: FileName
  INTEGER :: Producer
  INTEGER :: ErrNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenWriteEx_(pgdx,FileName,Producer,Compr, &
         ErrNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxopenwriteex_
  !DEC$ ATTRIBUTES STDCALL :: gdxopenwriteex_
  !DEC$ ATTRIBUTES ALIAS : 'gdxopenwriteex_'::gdxopenwriteex_
  INTEGER :: pgdx
  INTEGER :: FileName
  INTEGER :: Producer
  INTEGER :: Compr
  INTEGER :: ErrNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxResetSpecialValues_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxresetspecialvalues_
  !DEC$ ATTRIBUTES STDCALL :: gdxresetspecialvalues_
  !DEC$ ATTRIBUTES ALIAS : 'gdxresetspecialvalues_'::gdxresetspecialvalues_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetHasText_(pgdx,SyNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsethastext_
  !DEC$ ATTRIBUTES STDCALL :: gdxsethastext_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsethastext_'::gdxsethastext_
  INTEGER :: pgdx
  INTEGER :: SyNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetReadSpecialValues_(pgdx,AVals)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsetreadspecialvalues_
  !DEC$ ATTRIBUTES STDCALL :: gdxsetreadspecialvalues_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsetreadspecialvalues_'::gdxsetreadspecialvalues_
  INTEGER :: pgdx
  INTEGER :: AVals
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetSpecialValues_(pgdx,AVals)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsetspecialvalues_
  !DEC$ ATTRIBUTES STDCALL :: gdxsetspecialvalues_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsetspecialvalues_'::gdxsetspecialvalues_
  INTEGER :: pgdx
  INTEGER :: AVals
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetTextNodeNr_(pgdx,TxtNr,Node)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsettextnodenr_
  !DEC$ ATTRIBUTES STDCALL :: gdxsettextnodenr_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsettextnodenr_'::gdxsettextnodenr_
  INTEGER :: pgdx
  INTEGER :: TxtNr
  INTEGER :: Node
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetTraceLevel_(pgdx,N,s)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsettracelevel_
  !DEC$ ATTRIBUTES STDCALL :: gdxsettracelevel_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsettracelevel_'::gdxsettracelevel_
  INTEGER :: pgdx
  INTEGER :: N
  INTEGER :: s
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbIndxMaxLength_(pgdx,SyNr,LengthInfo)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbindxmaxlength_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbindxmaxlength_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbindxmaxlength_'::gdxsymbindxmaxlength_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: LengthInfo
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbMaxLength_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbmaxlength_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbmaxlength_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbmaxlength_'::gdxsymbmaxlength_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolAddComment_(pgdx,SyNr,Txt)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymboladdcomment_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymboladdcomment_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymboladdcomment_'::gdxsymboladdcomment_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: Txt
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolGetComment_(pgdx,SyNr,N,Txt)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbolgetcomment_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbolgetcomment_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbolgetcomment_'::gdxsymbolgetcomment_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: N
  INTEGER :: Txt
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolGetDomain_(pgdx,SyNr,DomainSyNrs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbolgetdomain_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbolgetdomain_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbolgetdomain_'::gdxsymbolgetdomain_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: DomainSyNrs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolGetDomainX_(pgdx,SyNr,DomainIDs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbolgetdomainx_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbolgetdomainx_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbolgetdomainx_'::gdxsymbolgetdomainx_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: DomainIDs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolDim_(pgdx,SyNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymboldim_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymboldim_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymboldim_'::gdxsymboldim_
  INTEGER :: pgdx
  INTEGER :: SyNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolInfo_(pgdx,SyNr,SyId,Dimen,Typ)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbolinfo_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbolinfo_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbolinfo_'::gdxsymbolinfo_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: SyId
  INTEGER :: Dimen
  INTEGER :: Typ
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolInfoX_(pgdx,SyNr,RecCnt,UserInfo, &
         ExplTxt)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbolinfox_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbolinfox_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbolinfox_'::gdxsymbolinfox_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: RecCnt
  INTEGER :: UserInfo
  INTEGER :: ExplTxt
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolSetDomain_(pgdx,DomainIDs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbolsetdomain_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbolsetdomain_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbolsetdomain_'::gdxsymbolsetdomain_
  INTEGER :: pgdx
  INTEGER :: DomainIDs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolSetDomainX_(pgdx,SyNr,DomainIDs)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsymbolsetdomainx_
  !DEC$ ATTRIBUTES STDCALL :: gdxsymbolsetdomainx_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsymbolsetdomainx_'::gdxsymbolsetdomainx_
  INTEGER :: pgdx
  INTEGER :: SyNr
  INTEGER :: DomainIDs
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSystemInfo_(pgdx,SyCnt,UelCnt)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxsysteminfo_
  !DEC$ ATTRIBUTES STDCALL :: gdxsysteminfo_
  !DEC$ ATTRIBUTES ALIAS : 'gdxsysteminfo_'::gdxsysteminfo_
  INTEGER :: pgdx
  INTEGER :: SyCnt
  INTEGER :: UelCnt
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELMaxLength_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelmaxlength_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelmaxlength_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelmaxlength_'::gdxuelmaxlength_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterDone_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelregisterdone_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelregisterdone_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelregisterdone_'::gdxuelregisterdone_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterMap_(pgdx,UMap,Uel)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelregistermap_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelregistermap_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelregistermap_'::gdxuelregistermap_
  INTEGER :: pgdx
  INTEGER :: UMap
  INTEGER :: Uel
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterMapStart_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelregistermapstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelregistermapstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelregistermapstart_'::gdxuelregistermapstart_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterRaw_(pgdx,Uel)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelregisterraw_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelregisterraw_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelregisterraw_'::gdxuelregisterraw_
  INTEGER :: pgdx
  INTEGER :: Uel
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterRawStart_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelregisterrawstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelregisterrawstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelregisterrawstart_'::gdxuelregisterrawstart_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterStr_(pgdx,Uel,UelNr)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelregisterstr_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelregisterstr_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelregisterstr_'::gdxuelregisterstr_
  INTEGER :: pgdx
  INTEGER :: Uel
  INTEGER :: UelNr
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterStrStart_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxuelregisterstrstart_
  !DEC$ ATTRIBUTES STDCALL :: gdxuelregisterstrstart_
  !DEC$ ATTRIBUTES ALIAS : 'gdxuelregisterstrstart_'::gdxuelregisterstrstart_
  INTEGER :: pgdx
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUMFindUEL_(pgdx,Uel,UelNr,UelMap)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxumfinduel_
  !DEC$ ATTRIBUTES STDCALL :: gdxumfinduel_
  !DEC$ ATTRIBUTES ALIAS : 'gdxumfinduel_'::gdxumfinduel_
  INTEGER :: pgdx
  INTEGER :: Uel
  INTEGER :: UelNr
  INTEGER :: UelMap
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUMUelGet_(pgdx,UelNr,Uel,UelMap)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxumuelget_
  !DEC$ ATTRIBUTES STDCALL :: gdxumuelget_
  !DEC$ ATTRIBUTES ALIAS : 'gdxumuelget_'::gdxumuelget_
  INTEGER :: pgdx
  INTEGER :: UelNr
  INTEGER :: Uel
  INTEGER :: UelMap
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUMUelInfo_(pgdx,UelCnt,HighMap)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxumuelinfo_
  !DEC$ ATTRIBUTES STDCALL :: gdxumuelinfo_
  !DEC$ ATTRIBUTES ALIAS : 'gdxumuelinfo_'::gdxumuelinfo_
  INTEGER :: pgdx
  INTEGER :: UelCnt
  INTEGER :: HighMap
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxCurrentDim_(pgdx)
  !DEC$ ATTRIBUTES DLLEXPORT :: gdxcurrentdim_
  !DEC$ ATTRIBUTES STDCALL :: gdxcurrentdim_
  !DEC$ ATTRIBUTES ALIAS : 'gdxcurrentdim_'::gdxcurrentdim_
  INTEGER :: pgdx
END FUNCTION
