MODULE gdxlfdef

  ! Lahey Fortran 95 procedure wrapper generated by apiwrapper for GAMS Version 24.0.2

  IMPLICIT NONE

  ! Constant declarations


  INTERFACE
  LOGICAL FUNCTION gdxCreate(pgdx, errMsg)
    INTEGER(KIND=4), INTENT(OUT) :: pgdx
    CHARACTER(LEN=*), INTENT(OUT) :: errMsg
  END FUNCTION
  END INTERFACE

  INTERFACE
  LOGICAL FUNCTION gdxCreateD(pgdx, dirName, errMsg)
    INTEGER(KIND=4), INTENT(OUT) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: dirName
    CHARACTER(LEN=*), INTENT(OUT) :: errMsg
  END FUNCTION
  END INTERFACE

  INTERFACE
  LOGICAL FUNCTION gdxCreateL(pgdx, libName, errMsg)
    INTEGER(KIND=4), INTENT(OUT) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: libName
    CHARACTER(LEN=*), INTENT(OUT) :: errMsg
  END FUNCTION
  END INTERFACE

  INTERFACE
  LOGICAL FUNCTION gdxFree(pgdx)
    INTEGER(KIND=4), INTENT(OUT) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  SUBROUTINE ConvF2PChar(fstr,pchar)
    CHARACTER(LEN=*) fstr
    CHARACTER(LEN=*) pchar
  END SUBROUTINE
  END INTERFACE

  INTERFACE
  SUBROUTINE ConvPChar2F(pchar,fstr)
    INTEGER pchar
    CHARACTER(LEN=*) fstr
  END SUBROUTINE
  END INTERFACE

  INTERFACE
  SUBROUTINE ConvStringPAS2F(passtr,fstr)
    CHARACTER(LEN=*) passtr
    CHARACTER(LEN=*) fstr
  END SUBROUTINE
  END INTERFACE

  INTERFACE
  SUBROUTINE ConvStringC2F(cstr,fstr)
    CHARACTER(LEN=*) cstr
    CHARACTER(LEN=*) fstr
  END SUBROUTINE
  END INTERFACE

  INTERFACE
  SUBROUTINE ConvStringF2PAS(fstr,passtr)
    CHARACTER(LEN=*) fstr
    CHARACTER(LEN=*) passtr
  END SUBROUTINE
  END INTERFACE

  INTERFACE
  SUBROUTINE ConvStringF2C(fstr,cstr)
    CHARACTER(LEN=*) fstr
    CHARACTER(LEN=*) cstr
  END SUBROUTINE
  END INTERFACE


  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymAdd(pgdx,AName,Txt,AIndx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: AName
    CHARACTER(LEN=*), INTENT(IN) :: Txt
    INTEGER(KIND=4), INTENT(IN) :: AIndx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymCount(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymGetInfo(pgdx,N,AName,Txt,AIndx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: N
    CHARACTER(LEN=*), INTENT(OUT) :: AName
    CHARACTER(LEN=*), INTENT(OUT) :: Txt
    INTEGER(KIND=4), INTENT(OUT) :: AIndx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymGetMapping(pgdx,N,orgIndx,newIndx, &
         autoIndex)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: N
    INTEGER(KIND=4), INTENT(OUT) :: orgIndx
    INTEGER(KIND=4), INTENT(OUT) :: newIndx
    INTEGER(KIND=4), INTENT(OUT) :: autoIndex
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymIndex(pgdx,V)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    REAL(KIND=8), INTENT(IN) :: V
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymName(pgdx,V,AName)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    REAL(KIND=8), INTENT(IN) :: V
    CHARACTER(LEN=*), INTENT(OUT) :: AName
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymNextNr(pgdx,NV)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: NV
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAcronymSetInfo(pgdx,N,AName,Txt,AIndx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: N
    CHARACTER(LEN=*), INTENT(IN) :: AName
    CHARACTER(LEN=*), INTENT(IN) :: Txt
    INTEGER(KIND=4), INTENT(IN) :: AIndx
  END FUNCTION
  END INTERFACE

  INTERFACE
  REAL(KIND=8) FUNCTION gdxAcronymValue(pgdx,AIndx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: AIndx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAddAlias(pgdx,Id1,Id2)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: Id1
    CHARACTER(LEN=*), INTENT(IN) :: Id2
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAddSetText(pgdx,Txt,TxtNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: Txt
    INTEGER(KIND=4), INTENT(OUT) :: TxtNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxAutoConvert(pgdx,NV)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: NV
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxClose(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataErrorCount(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataErrorRecord(pgdx,RecNr,KeyInt,Values)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: RecNr
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: KeyInt
    REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadDone(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadFilteredStart(pgdx,SyNr,FilterAction, &
         NrRecs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: FilterAction
    INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadMap(pgdx,RecNr,KeyInt,Values, &
         DimFrst)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: RecNr
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: KeyInt
    REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
    INTEGER(KIND=4), INTENT(OUT) :: DimFrst
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadMapStart(pgdx,SyNr,NrRecs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadRaw(pgdx,KeyInt,Values,DimFrst)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: KeyInt
    REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
    INTEGER(KIND=4), INTENT(OUT) :: DimFrst
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadRawFast(pgdx,SyNr,DP,NrRecs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    EXTERNAL DP
    INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadRawStart(pgdx,SyNr,NrRecs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadSlice(pgdx,UelFilterStr,Dimen, &
         DP)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: UelFilterStr
    INTEGER(KIND=4), INTENT(OUT) :: Dimen
    EXTERNAL DP
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadSliceStart(pgdx,SyNr,ElemCounts)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: ElemCounts
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadStr(pgdx,KeyStr,Values,DimFrst)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), DIMENSION(*), INTENT(OUT) :: KeyStr
    REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
    INTEGER(KIND=4), INTENT(OUT) :: DimFrst
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataReadStrStart(pgdx,SyNr,NrRecs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataSliceUELS(pgdx,SliceKeyInt,KeyStr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: SliceKeyInt
    CHARACTER(LEN=*), DIMENSION(*), INTENT(OUT) :: KeyStr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataWriteDone(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataWriteMap(pgdx,KeyInt,Values)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: KeyInt
    REAL(KIND=8), DIMENSION(*), INTENT(IN) :: Values
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataWriteMapStart(pgdx,SyId,ExplTxt, &
         Dimen,Typ,UserInfo)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: SyId
    CHARACTER(LEN=*), INTENT(IN) :: ExplTxt
    INTEGER(KIND=4), INTENT(IN) :: Dimen
    INTEGER(KIND=4), INTENT(IN) :: Typ
    INTEGER(KIND=4), INTENT(IN) :: UserInfo
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataWriteRaw(pgdx,KeyInt,Values)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: KeyInt
    REAL(KIND=8), DIMENSION(*), INTENT(IN) :: Values
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataWriteRawStart(pgdx,SyId,ExplTxt, &
         Dimen,Typ,UserInfo)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: SyId
    CHARACTER(LEN=*), INTENT(IN) :: ExplTxt
    INTEGER(KIND=4), INTENT(IN) :: Dimen
    INTEGER(KIND=4), INTENT(IN) :: Typ
    INTEGER(KIND=4), INTENT(IN) :: UserInfo
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataWriteStr(pgdx,KeyStr,Values)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: KeyStr
    REAL(KIND=8), DIMENSION(*), INTENT(IN) :: Values
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxDataWriteStrStart(pgdx,SyId,ExplTxt, &
         Dimen,Typ,UserInfo)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: SyId
    CHARACTER(LEN=*), INTENT(IN) :: ExplTxt
    INTEGER(KIND=4), INTENT(IN) :: Dimen
    INTEGER(KIND=4), INTENT(IN) :: Typ
    INTEGER(KIND=4), INTENT(IN) :: UserInfo
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxGetDLLVersion(pgdx,V)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(OUT) :: V
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxErrorCount(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxErrorStr(pgdx,ErrNr,ErrMsg)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: ErrNr
    CHARACTER(LEN=*), INTENT(OUT) :: ErrMsg
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxFileInfo(pgdx,FileVer,ComprLev)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(OUT) :: FileVer
    INTEGER(KIND=4), INTENT(OUT) :: ComprLev
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxFileVersion(pgdx,FileStr,ProduceStr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(OUT) :: FileStr
    CHARACTER(LEN=*), INTENT(OUT) :: ProduceStr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxFilterExists(pgdx,FilterNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: FilterNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxFilterRegister(pgdx,UelMap)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: UelMap
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxFilterRegisterDone(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxFilterRegisterStart(pgdx,FilterNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: FilterNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxFindSymbol(pgdx,SyId,SyNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: SyId
    INTEGER(KIND=4), INTENT(OUT) :: SyNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxGetElemText(pgdx,TxtNr,Txt,Node)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: TxtNr
    CHARACTER(LEN=*), INTENT(OUT) :: Txt
    INTEGER(KIND=4), INTENT(OUT) :: Node
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxGetLastError(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=8) FUNCTION gdxGetMemoryUsed(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxGetSpecialValues(pgdx,AVals)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: AVals
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxGetUEL(pgdx,UelNr,Uel)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: UelNr
    CHARACTER(LEN=*), INTENT(OUT) :: Uel
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxMapValue(pgdx,D,sv)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    REAL(KIND=8), INTENT(IN) :: D
    INTEGER(KIND=4), INTENT(OUT) :: sv
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxOpenAppend(pgdx,FileName,Producer,ErrNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: FileName
    CHARACTER(LEN=*), INTENT(IN) :: Producer
    INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxOpenRead(pgdx,FileName,ErrNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: FileName
    INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxOpenWrite(pgdx,FileName,Producer,ErrNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: FileName
    CHARACTER(LEN=*), INTENT(IN) :: Producer
    INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxOpenWriteEx(pgdx,FileName,Producer, &
         Compr,ErrNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: FileName
    CHARACTER(LEN=*), INTENT(IN) :: Producer
    INTEGER(KIND=4), INTENT(IN) :: Compr
    INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxResetSpecialValues(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSetHasText(pgdx,SyNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSetReadSpecialValues(pgdx,AVals)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    REAL(KIND=8), DIMENSION(*), INTENT(IN) :: AVals
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSetSpecialValues(pgdx,AVals)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    REAL(KIND=8), DIMENSION(*), INTENT(IN) :: AVals
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSetTextNodeNr(pgdx,TxtNr,Node)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: TxtNr
    INTEGER(KIND=4), INTENT(IN) :: Node
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSetTraceLevel(pgdx,N,s)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: N
    CHARACTER(LEN=*), INTENT(IN) :: s
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbIndxMaxLength(pgdx,SyNr,LengthInfo)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: LengthInfo
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbMaxLength(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolAddComment(pgdx,SyNr,Txt)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    CHARACTER(LEN=*), INTENT(IN) :: Txt
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolGetComment(pgdx,SyNr,N,Txt)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), INTENT(IN) :: N
    CHARACTER(LEN=*), INTENT(OUT) :: Txt
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolGetDomain(pgdx,SyNr,DomainSyNrs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: DomainSyNrs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolGetDomainX(pgdx,SyNr,DomainIDs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    CHARACTER(LEN=*), DIMENSION(*), INTENT(OUT) :: DomainIDs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolDim(pgdx,SyNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolInfo(pgdx,SyNr,SyId,Dimen,Typ)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    CHARACTER(LEN=*), INTENT(OUT) :: SyId
    INTEGER(KIND=4), INTENT(OUT) :: Dimen
    INTEGER(KIND=4), INTENT(OUT) :: Typ
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolInfoX(pgdx,SyNr,RecCnt,UserInfo, &
         ExplTxt)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    INTEGER(KIND=4), INTENT(OUT) :: RecCnt
    INTEGER(KIND=4), INTENT(OUT) :: UserInfo
    CHARACTER(LEN=*), INTENT(OUT) :: ExplTxt
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolSetDomain(pgdx,DomainIDs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: DomainIDs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSymbolSetDomainX(pgdx,SyNr,DomainIDs)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: SyNr
    CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: DomainIDs
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxSystemInfo(pgdx,SyCnt,UelCnt)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(OUT) :: SyCnt
    INTEGER(KIND=4), INTENT(OUT) :: UelCnt
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELMaxLength(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELRegisterDone(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELRegisterMap(pgdx,UMap,Uel)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: UMap
    CHARACTER(LEN=*), INTENT(IN) :: Uel
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELRegisterMapStart(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELRegisterRaw(pgdx,Uel)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: Uel
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELRegisterRawStart(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELRegisterStr(pgdx,Uel,UelNr)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: Uel
    INTEGER(KIND=4), INTENT(OUT) :: UelNr
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUELRegisterStrStart(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUMFindUEL(pgdx,Uel,UelNr,UelMap)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    CHARACTER(LEN=*), INTENT(IN) :: Uel
    INTEGER(KIND=4), INTENT(OUT) :: UelNr
    INTEGER(KIND=4), INTENT(OUT) :: UelMap
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUMUelGet(pgdx,UelNr,Uel,UelMap)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(IN) :: UelNr
    CHARACTER(LEN=*), INTENT(OUT) :: Uel
    INTEGER(KIND=4), INTENT(OUT) :: UelMap
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxUMUelInfo(pgdx,UelCnt,HighMap)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
    INTEGER(KIND=4), INTENT(OUT) :: UelCnt
    INTEGER(KIND=4), INTENT(OUT) :: HighMap
  END FUNCTION
  END INTERFACE

  INTERFACE
  INTEGER(KIND=4) FUNCTION gdxCurrentDim(pgdx)
    INTEGER(KIND=4), INTENT(IN) :: pgdx
  END FUNCTION
  END INTERFACE

END MODULE gdxlfdef

LOGICAL FUNCTION gdxCreate(pgdx, errMsg)
  INTEGER(KIND=4), INTENT(OUT) :: pgdx
  CHARACTER(LEN=*), INTENT(OUT) :: errMsg
  ML_EXTERNAL xcreate_
  CALL xcreate_(pgdx)
  gdxCreate = .TRUE.
END FUNCTION

LOGICAL FUNCTION gdxCreateD(pgdx, dirName, errMsg)
  INTEGER(KIND=4), INTENT(OUT) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: dirName
  CHARACTER(LEN=*), INTENT(OUT) :: errMsg
  ML_EXTERNAL xcreate_
  CALL xcreate_(pgdx)
  gdxCreateD = .TRUE.
END FUNCTION

LOGICAL FUNCTION gdxCreateL(pgdx, libName, errMsg)
  INTEGER(KIND=4), INTENT(OUT) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: libName
  CHARACTER(LEN=*), INTENT(OUT) :: errMsg
  ML_EXTERNAL xcreate_
  CALL xcreate_(pgdx)
  gdxCreateL = .TRUE.
END FUNCTION

LOGICAL FUNCTION gdxFree(pgdx)
  INTEGER(KIND=4), INTENT(OUT) :: pgdx
  ML_EXTERNAL xfree_
  CALL xfree_(pgdx)
  gdxFree = .TRUE.
END FUNCTION

SUBROUTINE ConvF2PChar(fstr,pchar)
  IMPLICIT NONE
  CHARACTER(LEN=*) fstr
  CHARACTER(LEN=*) pchar
  INTEGER n
  n = LEN_TRIM(fstr)
  pchar(1:n) = fstr(1:n)
  pchar(n+1:n+1) = char(0)
END SUBROUTINE

SUBROUTINE ConvPChar2F(pchar,fstr)
  IMPLICIT NONE
  INTEGER pchar
  CHARACTER(LEN=*) fstr
  INTEGER n
  INTEGER i
  CHARACTER c
  POINTER(p,c)
  n = LEN(fstr)
  fstr = ' '
  DO i=1,n
    p = pchar+i-1
    IF (ICHAR(c)==0) RETURN
    fstr(i:i) = c
  END DO
END SUBROUTINE

SUBROUTINE ConvStringPAS2F(passtr,fstr)
  IMPLICIT NONE
  CHARACTER(LEN=*) passtr
  CHARACTER(LEN=*) fstr
  INTEGER n
  n = ICHAR(passtr(1:1))
  IF (n>LEN(passtr)-1) THEN
    n = LEN(passtr)-1
  END IF
  IF (n>LEN(fstr)) THEN
    n = LEN(fstr)
  END IF
  fstr = ' '
  fstr(1:n) = passtr(2:n+1)
END SUBROUTINE

SUBROUTINE ConvStringC2F(cstr,fstr)
  IMPLICIT NONE
  CHARACTER(LEN=*) cstr
  CHARACTER(LEN=*) fstr
  INTEGER n
  fstr = ' '
  n = INDEX(cstr,char(0))
  IF (n==0) THEN
    fstr = cstr
  ELSE
    fstr(1:n-1) = cstr(1:n-1)
  END IF
END SUBROUTINE

SUBROUTINE ConvStringF2PAS(fstr,passtr)
  IMPLICIT NONE
  CHARACTER(LEN=*) fstr
  CHARACTER(LEN=*) passtr
  INTEGER n
  n = LEN_TRIM(fstr)
  IF (n>LEN(passtr)-1) THEN
    n = LEN(passtr)-1
  END IF
  passtr(1:1) = CHAR(n)
  passtr(2:n+1) = fstr(1:n)
END SUBROUTINE

SUBROUTINE ConvStringF2C(fstr,cstr)
  IMPLICIT NONE
  CHARACTER(LEN=*) fstr
  CHARACTER(LEN=*) cstr
  INTEGER n
  cstr=' '
  n = 1+LEN_TRIM(fstr)
  IF (n>LEN(cstr)) n = LEN(cstr)
  cstr=fstr
  cstr(n:n)=CHAR(0)
END SUBROUTINE


INTEGER(KIND=4) FUNCTION gdxAcronymAdd(pgdx,AName,Txt,AIndx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: AName
  CHARACTER(LEN=256) :: cpy_AName
  CHARACTER(LEN=*), INTENT(IN) :: Txt
  CHARACTER(LEN=256) :: cpy_Txt
  INTEGER(KIND=4), INTENT(IN) :: AIndx
  ML_EXTERNAL gdxacronymadd_
  INTEGER(KIND=4) gdxAcronymAdd_
  CALL ConvStringF2PAS(AName, cpy_AName)
  CALL ConvStringF2PAS(Txt, cpy_Txt)
  gdxAcronymAdd = gdxAcronymAdd_(val(pgdx), cpy_AName, cpy_Txt, val(AIndx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymCount(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxacronymcount_
  INTEGER(KIND=4) gdxAcronymCount_
  gdxAcronymCount = gdxAcronymCount_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymGetInfo(pgdx,N,AName,Txt,AIndx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: N
  CHARACTER(LEN=*), INTENT(OUT) :: AName
  CHARACTER(LEN=256) :: cpy_AName
  CHARACTER(LEN=*), INTENT(OUT) :: Txt
  CHARACTER(LEN=256) :: cpy_Txt
  INTEGER(KIND=4), INTENT(OUT) :: AIndx
  ML_EXTERNAL gdxacronymgetinfo_
  INTEGER(KIND=4) gdxAcronymGetInfo_
  gdxAcronymGetInfo = gdxAcronymGetInfo_(val(pgdx), val(N), cpy_AName &
         , cpy_Txt, AIndx)
  CALL ConvStringPAS2F(cpy_AName, AName)
  CALL ConvStringPAS2F(cpy_Txt, Txt)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymGetMapping(pgdx,N,orgIndx,newIndx, &
         autoIndex)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: N
  INTEGER(KIND=4), INTENT(OUT) :: orgIndx
  INTEGER(KIND=4), INTENT(OUT) :: newIndx
  INTEGER(KIND=4), INTENT(OUT) :: autoIndex
  ML_EXTERNAL gdxacronymgetmapping_
  INTEGER(KIND=4) gdxAcronymGetMapping_
  gdxAcronymGetMapping = gdxAcronymGetMapping_(val(pgdx), val(N), orgIndx &
         , newIndx, autoIndex)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymIndex(pgdx,V)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  REAL(KIND=8), INTENT(IN) :: V
  ML_EXTERNAL gdxacronymindex_
  INTEGER(KIND=4) gdxAcronymIndex_
  gdxAcronymIndex = gdxAcronymIndex_(val(pgdx), val(V))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymName(pgdx,V,AName)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  REAL(KIND=8), INTENT(IN) :: V
  CHARACTER(LEN=*), INTENT(OUT) :: AName
  CHARACTER(LEN=256) :: cpy_AName
  ML_EXTERNAL gdxacronymname_
  INTEGER(KIND=4) gdxAcronymName_
  gdxAcronymName = gdxAcronymName_(val(pgdx), val(V), cpy_AName)
  CALL ConvStringPAS2F(cpy_AName, AName)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymNextNr(pgdx,NV)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: NV
  ML_EXTERNAL gdxacronymnextnr_
  INTEGER(KIND=4) gdxAcronymNextNr_
  gdxAcronymNextNr = gdxAcronymNextNr_(val(pgdx), val(NV))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAcronymSetInfo(pgdx,N,AName,Txt,AIndx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: N
  CHARACTER(LEN=*), INTENT(IN) :: AName
  CHARACTER(LEN=256) :: cpy_AName
  CHARACTER(LEN=*), INTENT(IN) :: Txt
  CHARACTER(LEN=256) :: cpy_Txt
  INTEGER(KIND=4), INTENT(IN) :: AIndx
  ML_EXTERNAL gdxacronymsetinfo_
  INTEGER(KIND=4) gdxAcronymSetInfo_
  CALL ConvStringF2PAS(AName, cpy_AName)
  CALL ConvStringF2PAS(Txt, cpy_Txt)
  gdxAcronymSetInfo = gdxAcronymSetInfo_(val(pgdx), val(N), cpy_AName &
         , cpy_Txt, val(AIndx))
END FUNCTION

REAL(KIND=8) FUNCTION gdxAcronymValue(pgdx,AIndx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: AIndx
  ML_EXTERNAL gdxacronymvalue_
  REAL(KIND=8) gdxAcronymValue_
  gdxAcronymValue = gdxAcronymValue_(val(pgdx), val(AIndx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAddAlias(pgdx,Id1,Id2)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: Id1
  CHARACTER(LEN=256) :: cpy_Id1
  CHARACTER(LEN=*), INTENT(IN) :: Id2
  CHARACTER(LEN=256) :: cpy_Id2
  ML_EXTERNAL gdxaddalias_
  INTEGER(KIND=4) gdxAddAlias_
  CALL ConvStringF2PAS(Id1, cpy_Id1)
  CALL ConvStringF2PAS(Id2, cpy_Id2)
  gdxAddAlias = gdxAddAlias_(val(pgdx), cpy_Id1, cpy_Id2)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAddSetText(pgdx,Txt,TxtNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: Txt
  CHARACTER(LEN=256) :: cpy_Txt
  INTEGER(KIND=4), INTENT(OUT) :: TxtNr
  ML_EXTERNAL gdxaddsettext_
  INTEGER(KIND=4) gdxAddSetText_
  CALL ConvStringF2PAS(Txt, cpy_Txt)
  gdxAddSetText = gdxAddSetText_(val(pgdx), cpy_Txt, TxtNr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxAutoConvert(pgdx,NV)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: NV
  ML_EXTERNAL gdxautoconvert_
  INTEGER(KIND=4) gdxAutoConvert_
  gdxAutoConvert = gdxAutoConvert_(val(pgdx), val(NV))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxClose(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxclose_
  INTEGER(KIND=4) gdxClose_
  gdxClose = gdxClose_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataErrorCount(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxdataerrorcount_
  INTEGER(KIND=4) gdxDataErrorCount_
  gdxDataErrorCount = gdxDataErrorCount_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataErrorRecord(pgdx,RecNr,KeyInt,Values)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: RecNr
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: KeyInt
  REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
  ML_EXTERNAL gdxdataerrorrecord_
  INTEGER(KIND=4) gdxDataErrorRecord_
  gdxDataErrorRecord = gdxDataErrorRecord_(val(pgdx), val(RecNr), KeyInt &
         , Values)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadDone(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxdatareaddone_
  INTEGER(KIND=4) gdxDataReadDone_
  gdxDataReadDone = gdxDataReadDone_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadFilteredStart(pgdx,SyNr,FilterAction, &
         NrRecs)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: FilterAction
  INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  ML_EXTERNAL gdxdatareadfilteredstart_
  INTEGER(KIND=4) gdxDataReadFilteredStart_
  gdxDataReadFilteredStart = gdxDataReadFilteredStart_(val(pgdx), val(SyNr) &
         , FilterAction, NrRecs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadMap(pgdx,RecNr,KeyInt,Values, &
         DimFrst)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: RecNr
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: KeyInt
  REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
  INTEGER(KIND=4), INTENT(OUT) :: DimFrst
  ML_EXTERNAL gdxdatareadmap_
  INTEGER(KIND=4) gdxDataReadMap_
  gdxDataReadMap = gdxDataReadMap_(val(pgdx), val(RecNr), KeyInt, Values &
         , DimFrst)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadMapStart(pgdx,SyNr,NrRecs)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  ML_EXTERNAL gdxdatareadmapstart_
  INTEGER(KIND=4) gdxDataReadMapStart_
  gdxDataReadMapStart = gdxDataReadMapStart_(val(pgdx), val(SyNr) &
         , NrRecs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadRaw(pgdx,KeyInt,Values,DimFrst)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: KeyInt
  REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
  INTEGER(KIND=4), INTENT(OUT) :: DimFrst
  ML_EXTERNAL gdxdatareadraw_
  INTEGER(KIND=4) gdxDataReadRaw_
  gdxDataReadRaw = gdxDataReadRaw_(val(pgdx), KeyInt, Values, DimFrst)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadRawFast(pgdx,SyNr,DP,NrRecs)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  EXTERNAL DP
  INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  ML_EXTERNAL gdxdatareadrawfast_
  INTEGER(KIND=4) gdxDataReadRawFast_
  gdxDataReadRawFast = gdxDataReadRawFast_(val(pgdx), val(SyNr), DP &
         , NrRecs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadRawStart(pgdx,SyNr,NrRecs)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  ML_EXTERNAL gdxdatareadrawstart_
  INTEGER(KIND=4) gdxDataReadRawStart_
  gdxDataReadRawStart = gdxDataReadRawStart_(val(pgdx), val(SyNr) &
         , NrRecs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadSlice(pgdx,UelFilterStr,Dimen, &
         DP)
  USE gamsglobals
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: UelFilterStr
  CHARACTER(LEN=256), DIMENSION(MAX_INDEX_DIM) :: cpy_UelFilterStr
  INTEGER :: sidim_UelFilterStr
  INTEGER(KIND=4), INTENT(OUT) :: Dimen
  EXTERNAL DP
  INTEGER :: i_gdxDataReadSlice
  ML_EXTERNAL gdxdatareadslice_
  INTEGER(KIND=4) gdxDataReadSlice_
  sidim_UelFilterStr = gdxCurrentDim(pgdx)
  DO i_gdxDataReadSlice=1,sidim_UelFilterStr
    CALL ConvStringF2PAS(UelFilterStr(i_gdxDataReadSlice), cpy_UelFilterStr(i_gdxDataReadSlice))
  END DO
  gdxDataReadSlice = gdxDataReadSlice_(val(pgdx), cpy_UelFilterStr &
         , Dimen, DP)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadSliceStart(pgdx,SyNr,ElemCounts)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: ElemCounts
  ML_EXTERNAL gdxdatareadslicestart_
  INTEGER(KIND=4) gdxDataReadSliceStart_
  gdxDataReadSliceStart = gdxDataReadSliceStart_(val(pgdx), val(SyNr) &
         , ElemCounts)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadStr(pgdx,KeyStr,Values,DimFrst)
  USE gamsglobals
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), DIMENSION(*), INTENT(OUT) :: KeyStr
  CHARACTER(LEN=256), DIMENSION(MAX_INDEX_DIM) :: cpy_KeyStr
  INTEGER :: sidim_KeyStr
  REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: Values
  INTEGER(KIND=4), INTENT(OUT) :: DimFrst
  INTEGER :: i_gdxDataReadStr
  ML_EXTERNAL gdxdatareadstr_
  INTEGER(KIND=4) gdxDataReadStr_
  gdxDataReadStr = gdxDataReadStr_(val(pgdx), cpy_KeyStr, Values, DimFrst)
  sidim_KeyStr = gdxCurrentDim(pgdx)
  DO i_gdxDataReadStr=1,sidim_KeyStr
    CALL ConvStringPAS2F(cpy_KeyStr(i_gdxDataReadStr), KeyStr(i_gdxDataReadStr))
  END DO
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataReadStrStart(pgdx,SyNr,NrRecs)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), INTENT(OUT) :: NrRecs
  ML_EXTERNAL gdxdatareadstrstart_
  INTEGER(KIND=4) gdxDataReadStrStart_
  gdxDataReadStrStart = gdxDataReadStrStart_(val(pgdx), val(SyNr) &
         , NrRecs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataSliceUELS(pgdx,SliceKeyInt,KeyStr)
  USE gamsglobals
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: SliceKeyInt
  CHARACTER(LEN=*), DIMENSION(*), INTENT(OUT) :: KeyStr
  CHARACTER(LEN=256), DIMENSION(MAX_INDEX_DIM) :: cpy_KeyStr
  INTEGER :: sidim_KeyStr
  INTEGER :: i_gdxDataSliceUELS
  ML_EXTERNAL gdxdatasliceuels_
  INTEGER(KIND=4) gdxDataSliceUELS_
  gdxDataSliceUELS = gdxDataSliceUELS_(val(pgdx), SliceKeyInt, cpy_KeyStr)
  sidim_KeyStr = gdxCurrentDim(pgdx)
  DO i_gdxDataSliceUELS=1,sidim_KeyStr
    CALL ConvStringPAS2F(cpy_KeyStr(i_gdxDataSliceUELS), KeyStr(i_gdxDataSliceUELS))
  END DO
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteDone(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxdatawritedone_
  INTEGER(KIND=4) gdxDataWriteDone_
  gdxDataWriteDone = gdxDataWriteDone_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteMap(pgdx,KeyInt,Values)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: KeyInt
  REAL(KIND=8), DIMENSION(*), INTENT(IN) :: Values
  ML_EXTERNAL gdxdatawritemap_
  INTEGER(KIND=4) gdxDataWriteMap_
  gdxDataWriteMap = gdxDataWriteMap_(val(pgdx), KeyInt, Values)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteMapStart(pgdx,SyId,ExplTxt,Dimen, &
         Typ,UserInfo)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: SyId
  CHARACTER(LEN=256) :: cpy_SyId
  CHARACTER(LEN=*), INTENT(IN) :: ExplTxt
  CHARACTER(LEN=256) :: cpy_ExplTxt
  INTEGER(KIND=4), INTENT(IN) :: Dimen
  INTEGER(KIND=4), INTENT(IN) :: Typ
  INTEGER(KIND=4), INTENT(IN) :: UserInfo
  ML_EXTERNAL gdxdatawritemapstart_
  INTEGER(KIND=4) gdxDataWriteMapStart_
  CALL ConvStringF2PAS(SyId, cpy_SyId)
  CALL ConvStringF2PAS(ExplTxt, cpy_ExplTxt)
  gdxDataWriteMapStart = gdxDataWriteMapStart_(val(pgdx), cpy_SyId &
         , cpy_ExplTxt, val(Dimen), val(Typ), val(UserInfo))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteRaw(pgdx,KeyInt,Values)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN) :: KeyInt
  REAL(KIND=8), DIMENSION(*), INTENT(IN) :: Values
  ML_EXTERNAL gdxdatawriteraw_
  INTEGER(KIND=4) gdxDataWriteRaw_
  gdxDataWriteRaw = gdxDataWriteRaw_(val(pgdx), KeyInt, Values)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteRawStart(pgdx,SyId,ExplTxt,Dimen, &
         Typ,UserInfo)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: SyId
  CHARACTER(LEN=256) :: cpy_SyId
  CHARACTER(LEN=*), INTENT(IN) :: ExplTxt
  CHARACTER(LEN=256) :: cpy_ExplTxt
  INTEGER(KIND=4), INTENT(IN) :: Dimen
  INTEGER(KIND=4), INTENT(IN) :: Typ
  INTEGER(KIND=4), INTENT(IN) :: UserInfo
  ML_EXTERNAL gdxdatawriterawstart_
  INTEGER(KIND=4) gdxDataWriteRawStart_
  CALL ConvStringF2PAS(SyId, cpy_SyId)
  CALL ConvStringF2PAS(ExplTxt, cpy_ExplTxt)
  gdxDataWriteRawStart = gdxDataWriteRawStart_(val(pgdx), cpy_SyId &
         , cpy_ExplTxt, val(Dimen), val(Typ), val(UserInfo))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteStr(pgdx,KeyStr,Values)
  USE gamsglobals
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: KeyStr
  CHARACTER(LEN=256), DIMENSION(MAX_INDEX_DIM) :: cpy_KeyStr
  INTEGER :: sidim_KeyStr
  REAL(KIND=8), DIMENSION(*), INTENT(IN) :: Values
  INTEGER :: i_gdxDataWriteStr
  ML_EXTERNAL gdxdatawritestr_
  INTEGER(KIND=4) gdxDataWriteStr_
  sidim_KeyStr = gdxCurrentDim(pgdx)
  DO i_gdxDataWriteStr=1,sidim_KeyStr
    CALL ConvStringF2PAS(KeyStr(i_gdxDataWriteStr), cpy_KeyStr(i_gdxDataWriteStr))
  END DO
  gdxDataWriteStr = gdxDataWriteStr_(val(pgdx), cpy_KeyStr, Values)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxDataWriteStrStart(pgdx,SyId,ExplTxt,Dimen, &
         Typ,UserInfo)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: SyId
  CHARACTER(LEN=256) :: cpy_SyId
  CHARACTER(LEN=*), INTENT(IN) :: ExplTxt
  CHARACTER(LEN=256) :: cpy_ExplTxt
  INTEGER(KIND=4), INTENT(IN) :: Dimen
  INTEGER(KIND=4), INTENT(IN) :: Typ
  INTEGER(KIND=4), INTENT(IN) :: UserInfo
  ML_EXTERNAL gdxdatawritestrstart_
  INTEGER(KIND=4) gdxDataWriteStrStart_
  CALL ConvStringF2PAS(SyId, cpy_SyId)
  CALL ConvStringF2PAS(ExplTxt, cpy_ExplTxt)
  gdxDataWriteStrStart = gdxDataWriteStrStart_(val(pgdx), cpy_SyId &
         , cpy_ExplTxt, val(Dimen), val(Typ), val(UserInfo))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetDLLVersion(pgdx,V)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(OUT) :: V
  CHARACTER(LEN=256) :: cpy_V
  ML_EXTERNAL gdxgetdllversion_
  INTEGER(KIND=4) gdxGetDLLVersion_
  gdxGetDLLVersion = gdxGetDLLVersion_(val(pgdx), cpy_V)
  CALL ConvStringPAS2F(cpy_V, V)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxErrorCount(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxerrorcount_
  INTEGER(KIND=4) gdxErrorCount_
  gdxErrorCount = gdxErrorCount_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxErrorStr(pgdx,ErrNr,ErrMsg)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: ErrNr
  CHARACTER(LEN=*), INTENT(OUT) :: ErrMsg
  CHARACTER(LEN=256) :: cpy_ErrMsg
  ML_EXTERNAL gdxerrorstr_
  INTEGER(KIND=4) gdxErrorStr_
  gdxErrorStr = gdxErrorStr_(val(pgdx), val(ErrNr), cpy_ErrMsg)
  CALL ConvStringPAS2F(cpy_ErrMsg, ErrMsg)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFileInfo(pgdx,FileVer,ComprLev)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(OUT) :: FileVer
  INTEGER(KIND=4), INTENT(OUT) :: ComprLev
  ML_EXTERNAL gdxfileinfo_
  INTEGER(KIND=4) gdxFileInfo_
  gdxFileInfo = gdxFileInfo_(val(pgdx), FileVer, ComprLev)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFileVersion(pgdx,FileStr,ProduceStr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(OUT) :: FileStr
  CHARACTER(LEN=256) :: cpy_FileStr
  CHARACTER(LEN=*), INTENT(OUT) :: ProduceStr
  CHARACTER(LEN=256) :: cpy_ProduceStr
  ML_EXTERNAL gdxfileversion_
  INTEGER(KIND=4) gdxFileVersion_
  gdxFileVersion = gdxFileVersion_(val(pgdx), cpy_FileStr, cpy_ProduceStr)
  CALL ConvStringPAS2F(cpy_FileStr, FileStr)
  CALL ConvStringPAS2F(cpy_ProduceStr, ProduceStr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterExists(pgdx,FilterNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: FilterNr
  ML_EXTERNAL gdxfilterexists_
  INTEGER(KIND=4) gdxFilterExists_
  gdxFilterExists = gdxFilterExists_(val(pgdx), val(FilterNr))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterRegister(pgdx,UelMap)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: UelMap
  ML_EXTERNAL gdxfilterregister_
  INTEGER(KIND=4) gdxFilterRegister_
  gdxFilterRegister = gdxFilterRegister_(val(pgdx), val(UelMap))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterRegisterDone(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxfilterregisterdone_
  INTEGER(KIND=4) gdxFilterRegisterDone_
  gdxFilterRegisterDone = gdxFilterRegisterDone_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFilterRegisterStart(pgdx,FilterNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: FilterNr
  ML_EXTERNAL gdxfilterregisterstart_
  INTEGER(KIND=4) gdxFilterRegisterStart_
  gdxFilterRegisterStart = gdxFilterRegisterStart_(val(pgdx), val(FilterNr))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxFindSymbol(pgdx,SyId,SyNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: SyId
  CHARACTER(LEN=256) :: cpy_SyId
  INTEGER(KIND=4), INTENT(OUT) :: SyNr
  ML_EXTERNAL gdxfindsymbol_
  INTEGER(KIND=4) gdxFindSymbol_
  CALL ConvStringF2PAS(SyId, cpy_SyId)
  gdxFindSymbol = gdxFindSymbol_(val(pgdx), cpy_SyId, SyNr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetElemText(pgdx,TxtNr,Txt,Node)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: TxtNr
  CHARACTER(LEN=*), INTENT(OUT) :: Txt
  CHARACTER(LEN=256) :: cpy_Txt
  INTEGER(KIND=4), INTENT(OUT) :: Node
  ML_EXTERNAL gdxgetelemtext_
  INTEGER(KIND=4) gdxGetElemText_
  gdxGetElemText = gdxGetElemText_(val(pgdx), val(TxtNr), cpy_Txt &
         , Node)
  CALL ConvStringPAS2F(cpy_Txt, Txt)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetLastError(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxgetlasterror_
  INTEGER(KIND=4) gdxGetLastError_
  gdxGetLastError = gdxGetLastError_(val(pgdx))
END FUNCTION

INTEGER(KIND=8) FUNCTION gdxGetMemoryUsed(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxgetmemoryused_
  INTEGER(KIND=8) gdxGetMemoryUsed_
  gdxGetMemoryUsed = gdxGetMemoryUsed_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetSpecialValues(pgdx,AVals)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  REAL(KIND=8), DIMENSION(*), INTENT(IN OUT) :: AVals
  ML_EXTERNAL gdxgetspecialvalues_
  INTEGER(KIND=4) gdxGetSpecialValues_
  gdxGetSpecialValues = gdxGetSpecialValues_(val(pgdx), AVals)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxGetUEL(pgdx,UelNr,Uel)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: UelNr
  CHARACTER(LEN=*), INTENT(OUT) :: Uel
  CHARACTER(LEN=256) :: cpy_Uel
  ML_EXTERNAL gdxgetuel_
  INTEGER(KIND=4) gdxGetUEL_
  gdxGetUEL = gdxGetUEL_(val(pgdx), val(UelNr), cpy_Uel)
  CALL ConvStringPAS2F(cpy_Uel, Uel)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxMapValue(pgdx,D,sv)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  REAL(KIND=8), INTENT(IN) :: D
  INTEGER(KIND=4), INTENT(OUT) :: sv
  ML_EXTERNAL gdxmapvalue_
  INTEGER(KIND=4) gdxMapValue_
  gdxMapValue = gdxMapValue_(val(pgdx), val(D), sv)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenAppend(pgdx,FileName,Producer,ErrNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: FileName
  CHARACTER(LEN=256) :: cpy_FileName
  CHARACTER(LEN=*), INTENT(IN) :: Producer
  CHARACTER(LEN=256) :: cpy_Producer
  INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  ML_EXTERNAL gdxopenappend_
  INTEGER(KIND=4) gdxOpenAppend_
  CALL ConvStringF2PAS(FileName, cpy_FileName)
  CALL ConvStringF2PAS(Producer, cpy_Producer)
  gdxOpenAppend = gdxOpenAppend_(val(pgdx), cpy_FileName, cpy_Producer &
         , ErrNr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenRead(pgdx,FileName,ErrNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: FileName
  CHARACTER(LEN=256) :: cpy_FileName
  INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  ML_EXTERNAL gdxopenread_
  INTEGER(KIND=4) gdxOpenRead_
  CALL ConvStringF2PAS(FileName, cpy_FileName)
  gdxOpenRead = gdxOpenRead_(val(pgdx), cpy_FileName, ErrNr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenWrite(pgdx,FileName,Producer,ErrNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: FileName
  CHARACTER(LEN=256) :: cpy_FileName
  CHARACTER(LEN=*), INTENT(IN) :: Producer
  CHARACTER(LEN=256) :: cpy_Producer
  INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  ML_EXTERNAL gdxopenwrite_
  INTEGER(KIND=4) gdxOpenWrite_
  CALL ConvStringF2PAS(FileName, cpy_FileName)
  CALL ConvStringF2PAS(Producer, cpy_Producer)
  gdxOpenWrite = gdxOpenWrite_(val(pgdx), cpy_FileName, cpy_Producer &
         , ErrNr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxOpenWriteEx(pgdx,FileName,Producer,Compr, &
         ErrNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: FileName
  CHARACTER(LEN=256) :: cpy_FileName
  CHARACTER(LEN=*), INTENT(IN) :: Producer
  CHARACTER(LEN=256) :: cpy_Producer
  INTEGER(KIND=4), INTENT(IN) :: Compr
  INTEGER(KIND=4), INTENT(OUT) :: ErrNr
  ML_EXTERNAL gdxopenwriteex_
  INTEGER(KIND=4) gdxOpenWriteEx_
  CALL ConvStringF2PAS(FileName, cpy_FileName)
  CALL ConvStringF2PAS(Producer, cpy_Producer)
  gdxOpenWriteEx = gdxOpenWriteEx_(val(pgdx), cpy_FileName, cpy_Producer &
         , val(Compr), ErrNr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxResetSpecialValues(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxresetspecialvalues_
  INTEGER(KIND=4) gdxResetSpecialValues_
  gdxResetSpecialValues = gdxResetSpecialValues_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetHasText(pgdx,SyNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  ML_EXTERNAL gdxsethastext_
  INTEGER(KIND=4) gdxSetHasText_
  gdxSetHasText = gdxSetHasText_(val(pgdx), val(SyNr))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetReadSpecialValues(pgdx,AVals)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  REAL(KIND=8), DIMENSION(*), INTENT(IN) :: AVals
  ML_EXTERNAL gdxsetreadspecialvalues_
  INTEGER(KIND=4) gdxSetReadSpecialValues_
  gdxSetReadSpecialValues = gdxSetReadSpecialValues_(val(pgdx), AVals)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetSpecialValues(pgdx,AVals)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  REAL(KIND=8), DIMENSION(*), INTENT(IN) :: AVals
  ML_EXTERNAL gdxsetspecialvalues_
  INTEGER(KIND=4) gdxSetSpecialValues_
  gdxSetSpecialValues = gdxSetSpecialValues_(val(pgdx), AVals)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetTextNodeNr(pgdx,TxtNr,Node)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: TxtNr
  INTEGER(KIND=4), INTENT(IN) :: Node
  ML_EXTERNAL gdxsettextnodenr_
  INTEGER(KIND=4) gdxSetTextNodeNr_
  gdxSetTextNodeNr = gdxSetTextNodeNr_(val(pgdx), val(TxtNr), val(Node))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSetTraceLevel(pgdx,N,s)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: N
  CHARACTER(LEN=*), INTENT(IN) :: s
  CHARACTER(LEN=256) :: cpy_s
  ML_EXTERNAL gdxsettracelevel_
  INTEGER(KIND=4) gdxSetTraceLevel_
  CALL ConvStringF2PAS(s, cpy_s)
  gdxSetTraceLevel = gdxSetTraceLevel_(val(pgdx), val(N), cpy_s)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbIndxMaxLength(pgdx,SyNr,LengthInfo)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: LengthInfo
  ML_EXTERNAL gdxsymbindxmaxlength_
  INTEGER(KIND=4) gdxSymbIndxMaxLength_
  gdxSymbIndxMaxLength = gdxSymbIndxMaxLength_(val(pgdx), val(SyNr) &
         , LengthInfo)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbMaxLength(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxsymbmaxlength_
  INTEGER(KIND=4) gdxSymbMaxLength_
  gdxSymbMaxLength = gdxSymbMaxLength_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolAddComment(pgdx,SyNr,Txt)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  CHARACTER(LEN=*), INTENT(IN) :: Txt
  CHARACTER(LEN=256) :: cpy_Txt
  ML_EXTERNAL gdxsymboladdcomment_
  INTEGER(KIND=4) gdxSymbolAddComment_
  CALL ConvStringF2PAS(Txt, cpy_Txt)
  gdxSymbolAddComment = gdxSymbolAddComment_(val(pgdx), val(SyNr) &
         , cpy_Txt)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolGetComment(pgdx,SyNr,N,Txt)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), INTENT(IN) :: N
  CHARACTER(LEN=*), INTENT(OUT) :: Txt
  CHARACTER(LEN=256) :: cpy_Txt
  ML_EXTERNAL gdxsymbolgetcomment_
  INTEGER(KIND=4) gdxSymbolGetComment_
  gdxSymbolGetComment = gdxSymbolGetComment_(val(pgdx), val(SyNr) &
         , val(N), cpy_Txt)
  CALL ConvStringPAS2F(cpy_Txt, Txt)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolGetDomain(pgdx,SyNr,DomainSyNrs)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), DIMENSION(*), INTENT(IN OUT) :: DomainSyNrs
  ML_EXTERNAL gdxsymbolgetdomain_
  INTEGER(KIND=4) gdxSymbolGetDomain_
  gdxSymbolGetDomain = gdxSymbolGetDomain_(val(pgdx), val(SyNr), DomainSyNrs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolGetDomainX(pgdx,SyNr,DomainIDs)
  USE gamsglobals
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  CHARACTER(LEN=*), DIMENSION(*), INTENT(OUT) :: DomainIDs
  CHARACTER(LEN=256), DIMENSION(MAX_INDEX_DIM) :: cpy_DomainIDs
  INTEGER :: sidim_DomainIDs
  INTEGER :: i_gdxSymbolGetDomainX
  ML_EXTERNAL gdxsymbolgetdomainx_
  INTEGER(KIND=4) gdxSymbolGetDomainX_
  gdxSymbolGetDomainX = gdxSymbolGetDomainX_(val(pgdx), val(SyNr) &
         , cpy_DomainIDs)
  sidim_DomainIDs = gdxSymbolDim(pgdx, SyNr)
  DO i_gdxSymbolGetDomainX=1,sidim_DomainIDs
    CALL ConvStringPAS2F(cpy_DomainIDs(i_gdxSymbolGetDomainX), DomainIDs(i_gdxSymbolGetDomainX))
  END DO
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolDim(pgdx,SyNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  ML_EXTERNAL gdxsymboldim_
  INTEGER(KIND=4) gdxSymbolDim_
  gdxSymbolDim = gdxSymbolDim_(val(pgdx), val(SyNr))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolInfo(pgdx,SyNr,SyId,Dimen,Typ)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  CHARACTER(LEN=*), INTENT(OUT) :: SyId
  CHARACTER(LEN=256) :: cpy_SyId
  INTEGER(KIND=4), INTENT(OUT) :: Dimen
  INTEGER(KIND=4), INTENT(OUT) :: Typ
  ML_EXTERNAL gdxsymbolinfo_
  INTEGER(KIND=4) gdxSymbolInfo_
  gdxSymbolInfo = gdxSymbolInfo_(val(pgdx), val(SyNr), cpy_SyId, Dimen &
         , Typ)
  CALL ConvStringPAS2F(cpy_SyId, SyId)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolInfoX(pgdx,SyNr,RecCnt,UserInfo, &
         ExplTxt)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  INTEGER(KIND=4), INTENT(OUT) :: RecCnt
  INTEGER(KIND=4), INTENT(OUT) :: UserInfo
  CHARACTER(LEN=*), INTENT(OUT) :: ExplTxt
  CHARACTER(LEN=256) :: cpy_ExplTxt
  ML_EXTERNAL gdxsymbolinfox_
  INTEGER(KIND=4) gdxSymbolInfoX_
  gdxSymbolInfoX = gdxSymbolInfoX_(val(pgdx), val(SyNr), RecCnt, UserInfo &
         , cpy_ExplTxt)
  CALL ConvStringPAS2F(cpy_ExplTxt, ExplTxt)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolSetDomain(pgdx,DomainIDs)
  USE gamsglobals
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: DomainIDs
  CHARACTER(LEN=256), DIMENSION(MAX_INDEX_DIM) :: cpy_DomainIDs
  INTEGER :: sidim_DomainIDs
  INTEGER :: i_gdxSymbolSetDomain
  ML_EXTERNAL gdxsymbolsetdomain_
  INTEGER(KIND=4) gdxSymbolSetDomain_
  sidim_DomainIDs = gdxCurrentDim(pgdx)
  DO i_gdxSymbolSetDomain=1,sidim_DomainIDs
    CALL ConvStringF2PAS(DomainIDs(i_gdxSymbolSetDomain), cpy_DomainIDs(i_gdxSymbolSetDomain))
  END DO
  gdxSymbolSetDomain = gdxSymbolSetDomain_(val(pgdx), cpy_DomainIDs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSymbolSetDomainX(pgdx,SyNr,DomainIDs)
  USE gamsglobals
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: SyNr
  CHARACTER(LEN=*), DIMENSION(*), INTENT(IN) :: DomainIDs
  CHARACTER(LEN=256), DIMENSION(MAX_INDEX_DIM) :: cpy_DomainIDs
  INTEGER :: sidim_DomainIDs
  INTEGER :: i_gdxSymbolSetDomainX
  ML_EXTERNAL gdxsymbolsetdomainx_
  INTEGER(KIND=4) gdxSymbolSetDomainX_
  sidim_DomainIDs = gdxSymbolDim(pgdx, SyNr)
  DO i_gdxSymbolSetDomainX=1,sidim_DomainIDs
    CALL ConvStringF2PAS(DomainIDs(i_gdxSymbolSetDomainX), cpy_DomainIDs(i_gdxSymbolSetDomainX))
  END DO
  gdxSymbolSetDomainX = gdxSymbolSetDomainX_(val(pgdx), val(SyNr) &
         , cpy_DomainIDs)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxSystemInfo(pgdx,SyCnt,UelCnt)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(OUT) :: SyCnt
  INTEGER(KIND=4), INTENT(OUT) :: UelCnt
  ML_EXTERNAL gdxsysteminfo_
  INTEGER(KIND=4) gdxSystemInfo_
  gdxSystemInfo = gdxSystemInfo_(val(pgdx), SyCnt, UelCnt)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELMaxLength(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxuelmaxlength_
  INTEGER(KIND=4) gdxUELMaxLength_
  gdxUELMaxLength = gdxUELMaxLength_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterDone(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxuelregisterdone_
  INTEGER(KIND=4) gdxUELRegisterDone_
  gdxUELRegisterDone = gdxUELRegisterDone_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterMap(pgdx,UMap,Uel)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: UMap
  CHARACTER(LEN=*), INTENT(IN) :: Uel
  CHARACTER(LEN=256) :: cpy_Uel
  ML_EXTERNAL gdxuelregistermap_
  INTEGER(KIND=4) gdxUELRegisterMap_
  CALL ConvStringF2PAS(Uel, cpy_Uel)
  gdxUELRegisterMap = gdxUELRegisterMap_(val(pgdx), val(UMap), cpy_Uel)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterMapStart(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxuelregistermapstart_
  INTEGER(KIND=4) gdxUELRegisterMapStart_
  gdxUELRegisterMapStart = gdxUELRegisterMapStart_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterRaw(pgdx,Uel)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: Uel
  CHARACTER(LEN=256) :: cpy_Uel
  ML_EXTERNAL gdxuelregisterraw_
  INTEGER(KIND=4) gdxUELRegisterRaw_
  CALL ConvStringF2PAS(Uel, cpy_Uel)
  gdxUELRegisterRaw = gdxUELRegisterRaw_(val(pgdx), cpy_Uel)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterRawStart(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxuelregisterrawstart_
  INTEGER(KIND=4) gdxUELRegisterRawStart_
  gdxUELRegisterRawStart = gdxUELRegisterRawStart_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterStr(pgdx,Uel,UelNr)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: Uel
  CHARACTER(LEN=256) :: cpy_Uel
  INTEGER(KIND=4), INTENT(OUT) :: UelNr
  ML_EXTERNAL gdxuelregisterstr_
  INTEGER(KIND=4) gdxUELRegisterStr_
  CALL ConvStringF2PAS(Uel, cpy_Uel)
  gdxUELRegisterStr = gdxUELRegisterStr_(val(pgdx), cpy_Uel, UelNr)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUELRegisterStrStart(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxuelregisterstrstart_
  INTEGER(KIND=4) gdxUELRegisterStrStart_
  gdxUELRegisterStrStart = gdxUELRegisterStrStart_(val(pgdx))
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUMFindUEL(pgdx,Uel,UelNr,UelMap)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  CHARACTER(LEN=*), INTENT(IN) :: Uel
  CHARACTER(LEN=256) :: cpy_Uel
  INTEGER(KIND=4), INTENT(OUT) :: UelNr
  INTEGER(KIND=4), INTENT(OUT) :: UelMap
  ML_EXTERNAL gdxumfinduel_
  INTEGER(KIND=4) gdxUMFindUEL_
  CALL ConvStringF2PAS(Uel, cpy_Uel)
  gdxUMFindUEL = gdxUMFindUEL_(val(pgdx), cpy_Uel, UelNr, UelMap)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUMUelGet(pgdx,UelNr,Uel,UelMap)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(IN) :: UelNr
  CHARACTER(LEN=*), INTENT(OUT) :: Uel
  CHARACTER(LEN=256) :: cpy_Uel
  INTEGER(KIND=4), INTENT(OUT) :: UelMap
  ML_EXTERNAL gdxumuelget_
  INTEGER(KIND=4) gdxUMUelGet_
  gdxUMUelGet = gdxUMUelGet_(val(pgdx), val(UelNr), cpy_Uel, UelMap)
  CALL ConvStringPAS2F(cpy_Uel, Uel)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxUMUelInfo(pgdx,UelCnt,HighMap)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  INTEGER(KIND=4), INTENT(OUT) :: UelCnt
  INTEGER(KIND=4), INTENT(OUT) :: HighMap
  ML_EXTERNAL gdxumuelinfo_
  INTEGER(KIND=4) gdxUMUelInfo_
  gdxUMUelInfo = gdxUMUelInfo_(val(pgdx), UelCnt, HighMap)
END FUNCTION

INTEGER(KIND=4) FUNCTION gdxCurrentDim(pgdx)
  INTEGER(KIND=4), INTENT(IN) :: pgdx
  ML_EXTERNAL gdxcurrentdim_
  INTEGER(KIND=4) gdxCurrentDim_
  gdxCurrentDim = gdxCurrentDim_(val(pgdx))
END FUNCTION
