unit optdpdef; { delphi procedure wrapper generated by apiwrapper for gams version 24.0.2 }
{ function interface using a dll, pure delphi, static loading }

{$p- no open parameters ==> no maxlen byte}
{$v+ force var strings}
{$h- short only }

interface

uses
   sysutils,
   gmsgen;

const extlib = 'optdclib.dll';

const optdatanone    = 0;  { optdatatype }
      optdatainteger = 1;
      optdatadouble  = 2;
      optdatastring  = 3;
      optdatastrlist = 4;

const opttypeinteger   = 0;  { optoptiontype }
      opttypedouble    = 1;
      opttypestring    = 2;
      opttypeboolean   = 3;
      opttypeenumstr   = 4;
      opttypeenumint   = 5;
      opttypemultilist = 6;
      opttypestrlist   = 7;
      opttypemacro     = 8;
      opttypeimmediate = 9;

const optsubrequired = 0;  { optoptionsubtype }
      optsubnovalue  = 1;
      optsuboptional = 2;
      optsub2values  = 3;

const optmsginputecho    = 0;  { optmsgtype }
      optmsghelp         = 1;
      optmsgdefineerror  = 2;
      optmsgvalueerror   = 3;
      optmsgvaluewarning = 4;
      optmsgdeprecated   = 5;
      optmsgfileenter    = 6;
      optmsgfileleave    = 7;
      optmsgtoomanymsgs  = 8;
      optmsgusererror    = 9;

const optmapindicator  = 0;  { optvarequmaptype }
      optmapdefinedvar = 1;

type
   terrorcallback = function(errcount:integer; const msg:shortstring):integer; stdcall;

//tries to load dll from os default location
//name for the dll is automatic
function  optgetready(var msg: shortstring): boolean;
//tries to load dll from main program directory; if that fails
//loads dll from os default location
//name for the dll is automatic
function  optgetreadyx(var msg: shortstring): boolean;
//loads dll from specified directory
//name for the dll is automatic
function optgetreadyd(const dir: shortstring; var msg: shortstring): boolean;
//loads dll from the full path specified
//no changes are made to the name (platform and file extension)
function optgetreadyl(const libname: shortstring; var msg: shortstring): boolean;

//tries to load dll from os default location
//name for the dll is automatic
function optcreate(var popt: pointer; var msg: shortstring): boolean;
//tries to load dll from main program directory; if that fails
//loads dll from os default location
//name for the dll is automatic
function optcreatex(var popt: pointer; var msg: shortstring): boolean;
//loads dll from specified directory
//name for the dll is automatic
function optcreated(var popt: pointer; const dir: shortstring; var msg: shortstring): boolean;
//loads dll from the full path specified
function optcreatel(var popt: pointer; const libname: shortstring; var msg: shortstring): boolean;

procedure optfree  (var popt: pointer);

// functions and procedures
procedure optsetloadpath       (const s: shortstring); stdcall; external extlib;
procedure optgetloadpath       (var s: shortstring); stdcall; external extlib;
function  optreaddefinition    (popt: pointer; const fn: shortstring): integer; stdcall; external extlib;
function  optreadparameterfile (popt: pointer; const fn: shortstring): integer; stdcall; external extlib;
procedure optreadfromstr       (popt: pointer; const s: shortstring); stdcall; external extlib;
function  optwriteparameterfile(popt: pointer; const fn: shortstring): integer; stdcall; external extlib;
procedure optclearmessages     (popt: pointer); stdcall; external extlib;
procedure optaddmessage        (popt: pointer; const info: shortstring); stdcall; external extlib;
procedure optgetmessage        (popt: pointer; nrmsg: integer; out info: shortstring; out itype: integer); stdcall; external extlib;
procedure optresetall          (popt: pointer); stdcall; external extlib;
procedure optresetallrecent    (popt: pointer); stdcall; external extlib;
procedure optresetrecentchanges(popt: pointer); stdcall; external extlib;
procedure optshowhelp          (popt: pointer; const hlpid: shortstring); stdcall; external extlib;
function  optresetnr           (popt: pointer; anr: integer): integer; stdcall; external extlib;
function  optfindstr           (popt: pointer; const aname: shortstring; out anr: integer; out arefnr: integer): integer; stdcall; external extlib;
function  optgetinfonr         (popt: pointer; anr: integer; out adefined: integer; out adefinedr: integer; out arefnr: integer; out adatatype: integer; out aopttype: integer; out asubtype: integer): integer; stdcall; external extlib;
function  optgetvaluesnr       (popt: pointer; anr: integer; out asname: shortstring; out aival: integer; out adval: double; out asval: shortstring): integer; stdcall; external extlib;
function  optsetvaluesnr       (popt: pointer; anr: integer; aival: integer; adval: double; const asval: shortstring): integer; stdcall; external extlib;
function  optsetvalues2nr      (popt: pointer; anr: integer; aival: integer; adval: double; const asval: shortstring): integer; stdcall; external extlib;
procedure optversion           (popt: pointer; out sversion: shortstring); stdcall; external extlib;
procedure optdefinitionfile    (popt: pointer; out sfilename: shortstring); stdcall; external extlib;
function  optgetfromanystrlist (popt: pointer; idash: integer; out skey: shortstring; out sval: shortstring): integer; stdcall; external extlib;
function  optgetfromliststr    (popt: pointer; const skey: shortstring; out sval: shortstring): integer; stdcall; external extlib;
function  optlistcountstr      (popt: pointer; const skey: shortstring): integer; stdcall; external extlib;
function  optreadfromliststr   (popt: pointer; const skey: shortstring; ipos: integer; out sval: shortstring): integer; stdcall; external extlib;
function  optsynonymcount      (popt: pointer): integer; stdcall; external extlib;
function  optgetsynonym        (popt: pointer; nrsyn: integer; out ssyn: shortstring; out sname: shortstring): integer; stdcall; external extlib;
procedure optechoset           (popt: pointer; aival: integer); stdcall; external extlib;
function  opteolonlyset        (popt: pointer; aival: integer): integer; stdcall; external extlib;
procedure optnoboundsset       (popt: pointer; aival: integer); stdcall; external extlib;
procedure opterrorcount        (popt: pointer; out ierrors: integer; out iwarnings: integer); stdcall; external extlib;
function  optgetboundsint      (popt: pointer; anr: integer; out ilval: integer; out ihval: integer; out idval: integer): integer; stdcall; external extlib;
function  optgetboundsdbl      (popt: pointer; anr: integer; out dlval: double; out dhval: double; out ddval: double): integer; stdcall; external extlib;
function  optgetdefaultstr     (popt: pointer; anr: integer; out sval: shortstring): integer; stdcall; external extlib;
function  optgetintnr          (popt: pointer; anr: integer; out aival: integer): integer; stdcall; external extlib;
function  optgetint2nr         (popt: pointer; anr: integer; out aival: integer): integer; stdcall; external extlib;
function  optsetintnr          (popt: pointer; anr: integer; aival: integer): integer; stdcall; external extlib;
function  optsetint2nr         (popt: pointer; anr: integer; aival: integer): integer; stdcall; external extlib;
function  optgetstrnr          (popt: pointer; anr: integer; out asval: shortstring): integer; stdcall; external extlib;
function  optgetopthelpnr      (popt: pointer; anr: integer; out aname: shortstring; out ahc: integer; out agroup: integer): integer; stdcall; external extlib;
function  optgetenumhelp       (popt: pointer; anr: integer; aord: integer; out ahc: integer; out ahelpstr: shortstring): integer; stdcall; external extlib;
function  optgetenumstrnr      (popt: pointer; anr: integer; out asval: shortstring; out aord: integer): integer; stdcall; external extlib;
function  optgetenumcount      (popt: pointer; anr: integer; out acount: integer): integer; stdcall; external extlib;
function  optgetenumvalue      (popt: pointer; anr: integer; aord: integer; out avalint: integer; out avalstr: shortstring): integer; stdcall; external extlib;
function  optgetstr2nr         (popt: pointer; anr: integer; out asval: shortstring): integer; stdcall; external extlib;
function  optsetstrnr          (popt: pointer; anr: integer; const asval: shortstring): integer; stdcall; external extlib;
function  optsetstr2nr         (popt: pointer; anr: integer; const asval: shortstring): integer; stdcall; external extlib;
function  optgetdblnr          (popt: pointer; anr: integer; out adval: double): integer; stdcall; external extlib;
function  optgetdbl2nr         (popt: pointer; anr: integer; out adval: double): integer; stdcall; external extlib;
function  optsetdblnr          (popt: pointer; anr: integer; adval: double): integer; stdcall; external extlib;
function  optsetdbl2nr         (popt: pointer; anr: integer; adval: double): integer; stdcall; external extlib;
function  optgetvalstr         (popt: pointer; const aname: shortstring; out asval: shortstring): integer; stdcall; external extlib;
function  optgetval2str        (popt: pointer; const aname: shortstring; out asval: shortstring): integer; stdcall; external extlib;
function  optgetnamenr         (popt: pointer; anr: integer; out asname: shortstring): integer; stdcall; external extlib;
function  optgetdefinednr      (popt: pointer; anr: integer; out aival: integer): integer; stdcall; external extlib;
function  optgethelpnr         (popt: pointer; anr: integer; out asopt: shortstring; out ashelp: shortstring): integer; stdcall; external extlib;
function  optgetgroupnr        (popt: pointer; anr: integer; out aname: shortstring; out agroup: integer; out ahc: integer; out ahelp: shortstring): integer; stdcall; external extlib;
function  optgetgroupgrpnr     (popt: pointer; agroup: integer): integer; stdcall; external extlib;
function  optgetoptgroupnr     (popt: pointer; anr: integer): integer; stdcall; external extlib;
function  optgetdotoptnr       (popt: pointer; anr: integer; out vename: shortstring; out aobjnr: integer; out adim: integer; out avalue: double): integer; stdcall; external extlib;
function  optgetdotoptuel      (popt: pointer; anr: integer; adim: integer; out auel: shortstring): integer; stdcall; external extlib;
function  optgetvarequmapnr    (popt: pointer; maptype: integer; anr: integer; out equname: shortstring; out varname: shortstring; out equdim: integer; out vardim: integer; out avalue: integer): integer; stdcall; external extlib;
function  optgetequvarequmapnr (popt: pointer; maptype: integer; anr: integer; adim: integer; out aindex: shortstring): integer; stdcall; external extlib;
function  optgetvarvarequmapnr (popt: pointer; maptype: integer; anr: integer; adim: integer; out aindex: shortstring): integer; stdcall; external extlib;
function  optvarequmapcount    (popt: pointer; maptype: integer; out anrerrors: integer): integer; stdcall; external extlib;
function  optgetindicatornr    (popt: pointer; anr: integer; out equname: shortstring; out varname: shortstring; out equdim: integer; out vardim: integer; out avalue: integer): integer; stdcall; external extlib;
function  optgetequindicatornr (popt: pointer; anr: integer; adim: integer; out aindex: shortstring): integer; stdcall; external extlib;
function  optgetvarindicatornr (popt: pointer; anr: integer; adim: integer; out aindex: shortstring): integer; stdcall; external extlib;
function  optindicatorcount    (popt: pointer; out anrerrors: integer): integer; stdcall; external extlib;
function  optdotoptcount       (popt: pointer; out anrerrors: integer): integer; stdcall; external extlib;
function  optsetrefnr          (popt: pointer; anr: integer; arefnr: integer): integer; stdcall; external extlib;
function  optsetrefnrstr       (popt: pointer; const aopt: shortstring; arefnr: integer): integer; stdcall; external extlib;
function  optgetconstname      (popt: pointer; cgroup: integer; cindex: integer; out cname: shortstring): integer; stdcall; external extlib;
function  optgettypename       (popt: pointer; tnr: integer; out stname: shortstring): integer; stdcall; external extlib;
function  optlookup            (popt: pointer; const aopt: shortstring): integer; stdcall; external extlib;
procedure optreadfrompchar     (popt: pointer; p: pchar); stdcall; external extlib;
function  optgetnameopt        (popt: pointer; const asval: shortstring; out solver: shortstring; out opt: integer): integer; stdcall; external extlib;
function  optgetintstr         (popt: pointer; const aname: shortstring): integer; stdcall; external extlib;
function  optgetdblstr         (popt: pointer; const aname: shortstring): double; stdcall; external extlib;
procedure optsetintstr         (popt: pointer; const aname: shortstring; aival: integer); stdcall; external extlib;
procedure optsetdblstr         (popt: pointer; const aname: shortstring; adval: double); stdcall; external extlib;
procedure optsetstrstr         (popt: pointer; const aname: shortstring; const asval: shortstring); stdcall; external extlib;

// properties as functions and procedures
function  optcount           (popt: pointer): integer; stdcall; external extlib;
function  optmessagecount    (popt: pointer): integer; stdcall; external extlib;
function  optgroupcount      (popt: pointer): integer; stdcall; external extlib;
function  optrecentenabled   (popt: pointer): integer; stdcall; external extlib;
procedure optrecentenabledset(popt: pointer; const x: integer); stdcall; external extlib;

function  optgetdefinedstr(popt: pointer; const aname: shortstring): boolean; stdcall;
function  optgetstrstr(popt: pointer; const aname: shortstring): shortstring; stdcall;
implementation


procedure xcreate(var popt: pointer); stdcall; external extlib;
procedure xfree  (var popt: pointer); stdcall; external extlib;

function  bool_optgetdefinedstr(popt: pointer; const aname: shortstring): integer; stdcall; external extlib name 'optgetdefinedstr';
procedure sst_optgetstrstr(popt: pointer; const aname: shortstring; var sst_result: shortstring); stdcall; external extlib name 'optgetstrstr';

function  optgetdefinedstr(popt: pointer; const aname: shortstring): boolean; stdcall;
begin
result := bool_optgetdefinedstr(popt, aname) <> 0;
end;

function  optgetstrstr(popt: pointer; const aname: shortstring): shortstring; stdcall;
begin
sst_optgetstrstr(popt, aname, result);
end;
function optgetready(var msg: shortstring): boolean;
begin
msg := '';
result := true;
end;

function optgetreadyx(var msg: shortstring): boolean;
begin
msg := '';
result := true;
end;

function optgetreadyd(const dir: shortstring; var msg: shortstring): boolean;
begin
msg := '';
result := true;
end;

function optgetreadyl(const libname: shortstring; var msg: shortstring): boolean;
begin
msg := '';
result := true;
end;

function optcreate(var popt: pointer; var msg: shortstring): boolean;
begin
xcreate(popt);
if popt = nil
then
   begin
   result := false;
   msg := 'library is loaded but error while creating object';
   end
else
   result := true;
end;

function optcreatex(var popt: pointer; var msg: shortstring): boolean;
begin
xcreate(popt);
if popt = nil
then
   begin
   result := false;
   msg := 'library is loaded but error while creating object';
   end
else
   result := true;
end;

function optcreated(var popt: pointer; const dir: shortstring; var msg: shortstring): boolean;
begin
xcreate(popt);
if popt = nil
then
   begin
   result := false;
   msg := 'library is loaded but error while creating object';
   end
else
   result := true;
end;

function optcreatel(var popt: pointer; const libname: shortstring; var msg: shortstring): boolean;
begin
xcreate(popt);
if popt = nil
then
   begin
   result := false;
   msg := 'library is loaded but error while creating object';
   end
else
   result := true;
end;

procedure optfree  (var popt: pointer);
begin
xfree(popt);
end;

initialization

end.
