* Yields from May 17, 2000 (5/17/2000).

TABLE yield(ty,class,*)  yield curve

              term     interest
  t0.AAA         0     6.76
  t1.AAA         1     7.28
  t2.AAA         2     7.45
  t3.AAA         3     7.48
  t4.AAA         4     7.52
  t5.AAA         5     7.57
  t6.AAA         6     7.61
  t7.AAA         7     7.64
  t8.AAA         8     7.63
  t9.AAA         9     7.62
  t10.AAA        10    7.63
  t11.AAA        15    7.61
  t12.AAA        20    7.61
  t13.AAA        25    7.61
  t14.AAA        30    7.60
  t0.B3          0    11.4
  t1.B3          1    12.03
  t2.B3          2    12.26
  t3.B3          3    12.40
  t4.B3          4    12.50
  t5.B3          5    12.67
  t6.B3          6    12.69
  t7.B3          7    12.71
  t8.B3          8    12.63
  t9.B3          9    12.60
  t10.B3         10   12.74
  t11.B3         15   12.68
  t12.B3         20   12.73
  t13.B3         25   12.78
  t14.B3         30   12.65;
