* Factors from the complete 30-year data given
* in H. Dahl, Financial Optimization, Ch. 8.
* Data are transposed for convenience

TABLE betaTrans(t,j) Transposed factor loadings
            FF_1        FF_2     FF_3
2001        -0.18         0         0
2002        -0.16       0.02     -0.02
2003        -0.14       0.04     -0.03
2004        -0.12       0.06     -0.05
2005        -0.11       0.08     -0.06
2006        -0.10       0.10     -0.07
2007        -0.09       0.11     -0.09
2008        -0.08       0.12     -0.10
2009        -0.07       0.14     -0.12
2010        -0.06       0.14     -0.13
2011        -0.05       0.14     -0.15 ;


$ontext
* The following from H. Dahl, Financial Optimization, Ch. 8.
* These are the complete 30-year data, a 10-year subset is used above.

  TABLE betaTrans(t,j) Transposes factor loadings
            FF_1        FF_2     FF_3
   1        -0.18         0         0
   2        -0.16       0.02     -0.02
   3        -0.14       0.04     -0.03
   4        -0.12       0.06     -0.05
   5        -0.11       0.08     -0.06
   6        -0.10       0.10     -0.07
   7        -0.09       0.11     -0.09
   8        -0.08       0.12     -0.10
   9        -0.07       0.14     -0.12
  10        -0.06       0.14     -0.13
  11        -0.05       0.14     -0.15
  12        -0.04       0.14     -0.16
  13        -0.03       0.14     -0.18
  14        -0.03       0.13     -0.19
  15        -0.02       0.13     -0.21
  16        -0.02       0.12     -0.22
  17        -0.01       0.11     -0.24
  18          0         0.10     -0.25
  19          0         0.09     -0.27
  20          0         0.07     -0.28
  21         0.01       0.05     -0.30
  22         0.01       0.03     -0.31
  23         0.01       0.02     -0.33
  24         0.01       0.01     -0.34
  25         0.01         0      -0.36
  26          0        -0.01     -0.37
  27          0        -0.02     -0.39
  28        -0.01      -0.03     -0.41
  29        -0.02      -0.04     -0.43
  30        -0.03      -0.06     -0.45      /;
$offtext
