* Time sets

SETS
        tl       Liability time points   /tl0 * tl5/

        ty       Yield curve time points /t0 * t14/

        ts       Securities time points
        /1-Jun-00,  29-Jun-00,  19-Jul-00,  1-Aug-00,
     8-Aug-00,  1-Sep-00,   8-Sep-00,   1-Oct-00,  15-Oct-00,  9-Nov-00,
     1-Dec-00,  29-Dec-00,  1-Feb-01,   8-Feb-01,  1-Mar-01,   8-Mar-01,
     1-Apr-01,  15-Apr-01,  1-Jun-01,   29-Jun-01, 19-Jul-01,  1-Aug-01,
     1-Sep-01,  8-Sep-01,   1-Oct-01,   9-Nov-01,  1-Dec-01,   29-Dec-01,
     1-Feb-02,  15-Feb-02,  1-Mar-02,   8-Mar-02,  1-Apr-02,   1-Jun-02,
     29-Jun-02, 1-Jul-02,   1-Aug-02,   1-Sep-02,  8-Sep-02,   1-Oct-02,
     9-Nov-02,  1-Dec-02,   1-Feb-03,   1-Mar-03,  8-Mar-03,   1-Apr-03,
     1-Jun-03,  1-Aug-03,   15-Aug-03,  1-Sep-03,  8-Sep-03,   1-Oct-03,
     9-Nov-03,  1-Dec-03,   1-Feb-04,   1-Mar-04,  8-Mar-04,   1-Apr-04,
     1-Jun-04,  1-Aug-04,   15-Aug-04,  1-Sep-04,  8-Sep-04,   1-Oct-04,
     9-Nov-04,  1-Dec-04,   1-Mar-05,   8-Mar-05,  1-Apr-05,   1-Jun-05,
     1-Sep-05,  8-Sep-05,   1-Oct-05,   1-Dec-05,  1-Mar-06,   8-Mar-06,
     1-Jun-06,  1-Sep-06,   1-Dec-06,   1-Mar-07,  1-Jun-07,   1-Jul-07,
     1-Sep-07,  1-Dec-07,   15-Feb-08,  1-Mar-08,  1-Jun-08,   1-Sep-08,
     1-Dec-08,  1-Mar-09,   1-Jun-09,   1-Sep-09,  1-Apr-10/

     tf      Factor time points  /tf0  * tf12/;
