set ath author /
"Adhya, N"
"Adjiman, C S"
"Aggarwal, A"
"Ahmad, M"
"Alatorre, J"
"Andersen, E"
"Anderson, D"
"Anitescu, M"
"ARCNET"
"Aronofsky, J S"
"Ascher, U M"
"Audet, C"
"Averick, B M"
"Back, T"
"Balakrishnan, N"
"Balard, C L"
"Beasley, J E"
"Beauvais, J"
"Belotti, P"
"Beltramo, M A"
"Ben-Tal, A"
"Benson, H P"
"Bergendorff, H"
"Berna, T"
"Bertsekas, D P"
"Betts, J"
"Biegler, L T"
"Biggar, D R"
"Birge, J R"
"Blair, P D"
"Blitzer, C"
"Boehringer, C"
"Boger, G M"
"Bollapragada, S"
"Bondarenko, A S"
"Borland"
"Borndoerfer, R"
"Bosch, R A"
"Boussofiane"
"Box, G E P"
"Boyd, S"
"Bracken, J"
"Breton, M"
"Brimberg, J"
"Brooke, A"
"Brown, M"
"Bryson, A E"
"Bulirsch, R"
"Bureau T E"
"Burkard, R E"
"Bussieck, M R"
"Butzer, P L"
"C. Strugarek"
"Capriz, G"
"Carlson, R C"
"Carter, R G"
"Cattaneo, A"
"CDC"
"Cesari, L"
"Chakravarty, S"
"Chen, C H"
"Chenery, H B"
"Cheng, H"
"Chlond, M J"
"Cho, B R"
"Choksi, A M"
"Chou, C Y"
"Choypeng, P"
"Cimatti, G"
"Claessens, M T"
"Clark, R H"
"Coello Coello, C A"
"Condon, T"
"Cox, D R"
"Cox, L H"
"Dahl, H"
"Dammert, A"
"Daniel, R C"
"Dantzig, G B"
"Day, R E"
"de Wetering, A V"
"de Wolf, D"
"Deaven, D M"
"Deb, K"
"den Hertog, D"
"Devarajan, S"
"di Tella, G"
"Dirkse, S P"
"Dolan, E D"
"Doufherty, D"
"Drud, A S"
"Dudeney, H E"
"Duloy, J H"
"Dutton, J M"
"Dyson"
"Edgar, T F"
"Eiger, G"
"El-Said, M"
"Elbers, A W"
"Eldersveld, S"
"Ellison, E F D"
"Erjavec, J"
"Ermoliev, Y"
"Esposito, W R"
"Fair, R C"
"Fasano, A"
"Feenstra, R"
"Ferris, M C"
"Florios, K"
"Floudas, C A"
"Foulds, L R"
"Fourer, R"
"Friedman, A"
"Fulkerson"
"Fullerton Don"
"GAMS Development Corporation"
"GAMS Model Library"
"Garbiras, M"
"Gardner, M"
"Garver, L L"
"Gasawa, K"
"Gay, D M"
"Gdanska, P"
"Gershovitz, V"
"Gill, P E"
"Gilmore, P C"
"Glenshaw, P"
"Glowinski, R"
"Goemans M.X."
"Golan, A"
"Gomory, R E"
"Goreaux, L M"
"Goyal, M"
"Goyal, S K"
"Graham, R L"
"Greening, D"
"Groetschel, M"
"Grossmann, I E"
"Gueret, C"
"Guignard, M"
"Gumus, Z H"
"Gunasekaran, A"
"Gunluk, O"
"Gutierrez, R A"
"H. Heitsch"
"Hallet, A J H"
"Hamada, K"
"Handbook of Test Problems"
"Hansen, P"
"Hansen, T"
"Hanson, K"
"Harding, S T"
"Harjunkoski, I"
"Harker, P T"
"Harrison, S"
"Hashimoto, H"
"Haugland, D"
"Haverly, C A"
"Heipcke, S"
"Hesamzadeh, M R"
"Hieu, P S"
"Hillier, F S"
"Himmelblau, D M"
"Hitch, C J"
"Ho, K M"
"Ho, Y"
"Hock, W"
"Horowitz, J L"
"Hosoe, N"
"House, B"
"Huffman, W"
"Hunter, W G"
"Husain, T"
"IBM"
"ILOG"
"IMSL Inc"
"Infanger, G"
"Inman, R"
"Itoh, H"
"Jain, V"
"Johnson"
"Jooste, A"
"Jornsten, K"
"Judge, G"
"Judge, G G"
"Juenger, M"
"Kall, P"
"Kallrath, J"
"Kalvelagen, E"
"Kamiya, K"
"Karisch, S E"
"Kasnagoklu, H"
"Kehoe, T"
"Kelly, J P"
"Kendrick, D"
"Kennington, L"
"Kernighan, B W"
"Kilkenny, M"
"Kindleberger, C P"
"King, A J"
"Klepeis, J L"
"Klingman, D"
"Kocis, G R"
"Konno, H"
"Kotz, J"
"Kreuzer, P"
"Kucherenko, S"
"Kuijlaars, A"
"Kuno, T"
"Kutcher, G P"
"Laguna, M"
"Lasdon, L S"
"Lawler, E L"
"Le, Q H"
"Le-Si, V"
"Lebret, H"
"Lenstra, J K"
"Lewis, J"
"Liberti, L"
"Lieberman, G J"
"Lih, K"
"Linderoth, J"
"Linderoth, J T"
"Lobo, M S"
"Locke, M"
"Loebel, A"
"Lopez de Silanes, F"
"Louveaux, F V"
"Lu, Z"
"Macewan, A"
"MacGregor, J F"
"Mackinnon, J"
"Maculan, N"
"Mallik, S"
"Mangasarian, O L"
"Manne, A S"
"Maria, G"
"Markowitz, H M"
"Markusen, J R"
"Martello, S"
"Martikainen T"
"Mathematica"
"Mattheij, R M M"
"Mavrotas, G"
"McCormick, G P"
"Meeraus, A"
"Meeraus, W H"
"Melton, J W"
"Meneses, C N"
"Mennes, L B M"
"Meyer, C A"
"Meyer, R R"
"Michna, M"
"Miller, C E"
"Miller, D"
"Miller, M H"
"Miller, R E"
"Mitra, P"
"Mitsos, A"
"Mladenovic, N"
"Moon, I"
"Morari, M"
"More, J J"
"Morris, J R"
"Mulvey, J"
"Murphy, F H"
"Murray, W"
"Murtagh, B A"
"Napier, A"
"Nelson, C R"
"Nemhauser, G L"
"Nerz, E"
"Neumaier, A"
"Ni, H"
"Norton, R D"
"O'Brochta, D"
"O'Mara, G T"
"Ogura, A"
"Oliveira, C A S"
"Olubode-Awosola, O O"
"Ortega, F"
"Palaniappan, S"
"Palmer, K H"
"Panton, D M"
"Pardalos, P M"
"Patil, R J"
"Paules IV, G E"
"Pereira, M V F"
"Perroni, C"
"Pesch, H J"
"Petersen, C C"
"Petterson, F"
"Phan, S H"
"Phillips, M"
"Phillips, M D"
"Pindyck, R S"
"Pinter, J D"
"Pinto, L M V G"
"Plateau M.C."
"Pochet, Y"
"Porn, R"
"Preckel, P V"
"Primicerio, M"
"Prins, C"
"Puakpong, P"
"Raduchel, W J"
"Ragavan, R"
"Ramamurti, M"
"Raman, R"
"Ramsey, F P"
"Rasmussen K.M."
"Rebennack, S"
"Reinelt, G"
"Rendl, F"
"Richels, R G"
"Rinnoy Kan, A H G"
"Robbins, A"
"Robinson, S"
"Rohde, S M"
"Rosenborg, A"
"Rosenbrock, H H"
"Rosenthal, R E"
"Rosenwein, M"
"Rothschild, B J"
"Rowse"
"Russell, R D"
"Rutherford, T F"
"Saff, E B"
"Sahinidis, N"
"Samuelson"
"Sandgren, E"
"Saunders, M A"
"Savant, M"
"Scandizzo, P L"
"Scarf, H"
"Schittkowski, K"
"Schoen, D J"
"Schrijver, A"
"Schweiger, C A"
"Serban, R"
"Sevaux, M"
"Sharov, A F"
"Shcherbina, O"
"Shepotylo, O"
"Sherali, H D"
"Shmoys, D B"
"Shoven, J"
"Siddall, J N"
"Silver, E A"
"Skouras, S"
"Skrifvars, H"
"Sloane, N J A"
"Smeers, Y"
"Snell, E J"
"So, K C"
"Somwaru, A"
"Soyster, A L"
"Spencer, J E"
"Stehouwer, H P"
"Stinstra, E"
"Stoutjesdijk, A J"
"Stutz, J"
"Suh, J S"
"Syrquin, M"
"Takayama, T"
"Tarr, D"
"Tawarmalani, M"
"Taylor, L"
"Tayyabkhan, M T"
"Teisberg, T J"
"Tendulkar, S"
"Thanassoulis"
"Thienel, S"
"Thoai, N V"
"Thompson, G"
"Thor, S"
"Thorpe, S"
"Tierney, L"
"Tjoa, I B"
"Toczek, J"
"Torma, H"
"Toth, P"
"Trefethen, N"
"Tsitsiklis, J N"
"Tucker, A W"
"Turkay M."
"Turvey, R"
"van Dijk, N M"
"van Schalkwyk H D"
"Vandenberghe, L"
"Vanderbei, R"
"Vecchietti, A"
"Vestjens, A"
"Vietoriscz, T"
"Viswanathan, J"
"von Stryk, O"
"von Thunen"
"Voss, S"
"W. Roemisch"
"Wagner, H M"
"Wall, T W"
"Wallace, S W"
"Westerberg, A W"
"Westerlund, T"
"Westphal, L E"
"Wets, R J"
"Weyant, J P"
"Whalley, J"
"Wiegele A."
"Wiens, T B"
"Williams, H P"
"Williamson, D P"
"Wolfe, P"
"Wollenberg, B F"
"Wolsey, L"
"Wolsey, L A"
"Wood, A J"
"Woodruff, D L"
"Woolsey, R E D"
"World Bank"
"Wright, M H"
"Wright, S I"
"Xue, G L"
"Yee, T F"
"Yli-Olli, P"
"Zemlin, R A"
"Zenios, S A"
"Zimmermann, U T"
"Zloof, M M"
"Zwaneveld, P J"
/
set r references /
r1  "Dantzig, G B, Chapter 3.3. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r2  "Rosenthal, R E, Chapter 2: A GAMS Tutorial. In GAMS: A User's Guide. The Scientific Press, Redwood City, California, 1988."
r3  "Dantzig, G B, Chapter 3.4. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r4  "Dantzig, G B, Chapter 3.5. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r5  "Dantzig, G B, Chapter 3.6. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r6  "Dantzig, G B, Chapter 3.7. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r7  "Dantzig, G B, Chapter 17.3. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r8  "Dantzig, G B, Chapter 27.1. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r9  "Dantzig, G B, Chapter 28. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r10  "CDC, APEX-III Reference Manual Version 1.2, Control Data Corporation, Minneapolis, 1980. MIP Sample Problem"
r11  "ARCNET, ARCNET User Guide, Analysis, Research and Computation, Austin, Texas, 1982."
r12  "Ellison, E F D, and Mitra, P, UIMP - User Interface for Mathematical Programming. ACM Transactions on Mathematical Software 8, 2 (1982)."
r13  "Day, R E, and Williams, H P, MAGIC: The design and use of an interactive modeling language for mathematical programming. Tech. rep., Department Business Studies, University of Edinburgh, 1982."
r14  "Williams, H P, Model Building in Mathematical Programming. John Wiley and Sons, 1978."
r15  "Choksi, A M, Meeraus, A, and Stoutjesdijk, A J, The Planning of Investment Programs in the Fertilizer Industry. The John Hopkins University Press, Baltimore and London, 1980."
r16  "Kendrick, D, Meeraus, A, and Alatorre, J, The Planning of Investment Programs in the Steel Industry. The Johns Hopkins University Press, Baltimore and London, 1984."
r17  "Bracken, J, and McCormick, G P, Chapter 2. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 22-27."
r18  "Bracken, J, and McCormick, G P, Chapter 3. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 28-36."
r19  "Bracken, J, and McCormick, G P, Chapter 4. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r20  "Bracken, J, and McCormick, G P, Chapter 5. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 48-49."
r21  "Bracken, J, and McCormick, G P, Chapter 6. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r22  "Bracken, J, and McCormick, G P, Chapter 8.2. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 86-88."
r23  "Bracken, J, and McCormick, G P, Chapter 8.4. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 89-90."
r24  "Bracken, J, and McCormick, G P, Chapter 8.5. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 90-92."
r25  "Bracken, J, and McCormick, G P, Chapter 9. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 94-100."
r26  "Bracken, J, and McCormick, G P, Chapter 10.2. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r27  "Pindyck, R S, Gains to Producers from the Cartelization of Exhaustible Resources. Review of Economics and Statistics 60 (1978), 238-251."
r28  "Zloof, M M, Query-by-Example: A Data Base Language. IBM Systems Journal 16, 4 (1977), 324-343."
r29  "Manne, A S, and Vietoriscz, T, Chemical Processes, Plant Location, and Economies of Scale. In Manne, A S, and Markowitz, H M, Eds, Studies in Process Analysis. John Wiley and Sons, New York and London, 1963, p. 136."
r30  "Brown, M, Dammert, A, Meeraus, A, and Stoutjesdijk, A J, Worldwide Investment Analysis - The Case of Aluminum. Tech. rep., The World Bank, 1983."
r31  "Kendrick, D, Meeraus, A, and Suh, J S, Oil Refinery Modeling with the GAMS language. Tech. rep., Center of Energy Studies, University of Texas, 1981."
r32  "Chenery, H B, and Raduchel, W J, Substitution and Structural Change. In Chenery, H B, Ed, Structural Change and Development Policy. Oxford University Press, New York and Oxford, 1979."
r33  "Chenery, H B, and Macewan, A, Chapter 9: Optimal Patterns of Growth and Aid. In Chenery, H B, Ed, Structural Change and Development Policy. Oxford University Press, New York and Oxford, 1979."
r34  "Manne, A S, Dinamico, A Multi-Sector, Multi-skill Model. In Goreaux, L M, and Manne, A S, Eds, Multi-level Planning: Case Studies in Mexico. North-Holland, Amsterdam, 1973."
r35  "Himmelblau, D M, Problem Number 16. In Applied Nonlinear Programming. Mc Graw Hill, New York, 1972."
r36  "Fourer, R, Modeling Languages Versus Matrix Generators for Linear Programming. ACM Transaction on Mathematical Software 9, 2 (1983), 143-183."
r37  "Kendrick, D, Chapter 3: A Relational Database of the US Economy. In Kindleberger, C P, and di Tella, G, Eds, Economics in the Long View, Essays in the Honor of W W Rostow. Macmillan, London, 1982."
r38  "Lewis, J, and Robinson, S, Chapter 11. In Chenery, H B, Robinson, S, and Syrquin, M, Eds, Industrialization and Growth: A Comparative Study. Oxford University Press, London, 1986."
r39  "Kendrick, D, Style in Multisector Modeling. In Hallet, A J H, Ed, Applied Decision Analysis and Economic Behavior. Kluwer and Nijhoff, Boston and The Hague, 1984."
r40  "Norton, R D, and Scandizzo, P L, Market Equilibrium Computations in Activity Analysis Models. Operations Research 29, 2 (1981)."
r41  "Williams, H P, Experiments in the formulation of Integer Programming Problems. Mathematical Programming Study 2 (1974)."
r42  "Kendrick, D, and Taylor, L, Numerical methods and Nonlinear Optimizing models for Economic Planning. In Chenery, H B, Ed, Studies of Development Planning. Harvard University Press, 1971."
r43  "Chakravarty, S, Optimum Savings with a Finite Planning Horizon. International Economic Review 3 (1962), 338-355."
r44  "Mennes, L B M, and Stoutjesdijk, A J, Multicountry Investment Analysis. The John Hopkins University Press, Baltimore and London, 1986."
r45  "Dammert, A, and Palaniappan, S, Modeling Investments in the World Copper Sector. The University of Texas Press, Austin, Texas, 1985."
r46  "Melton, J W, An Investment Planning Model for an Oil Shale Industry in the Piceance Basin. PhD thesis, Center for Economic Research, University of Texas, 1982."
r47  "Blitzer, C, Meeraus, A, and Stoutjesdijk, A J, A Dynamic model of OPEC Trade and Production. Journal of Development Economics, 2 (1975), 318-335."
r48  "Suh, J S, An Investment Planning Model for the Oil-Refining and Petro-chemical Industries in Korea. Tech. rep., Center for Economic Research, University of Texas, 1981."
r49  "Husain, T, and Inman, R, A Model for Estimating the Effects of Credit pricing on Farm level employment and income distribution. Tech. rep., The World Bank, 1977."
r50  "CDC, IFPS/OPTIMIM - Users Manual, Control Data Corporation, Minneapolis, 1984."
r51  "World Bank, Yemen Arab Republic - Manufacturing Industry: Performance, Policies and Prospectives. Tech. rep., The World Bank, 1982."
r52  "Manne, A S, Nelson, C R, So, K C, and Weyant, J P, CPM: A Contingency Planning Model of the International Oil Market, International Energy Program Report. Tech. rep., Stanford University, 1982."
r53  "Manne, A S, and Beltramo, M A, GTM: An International Gas Trade Model ,International Energy Program Report. Stanford University, 1984."
r54  "Turvey, R, and Anderson, D, Chapter 8: Electricity Development in Turkey: A Case Study using Linear Programming. In Electricity Economics: Essays and Case Studies. Johns Hopkins University Press, Baltimore and London, 1977."
r55  "World Bank, Pakistan Punjab Livestock Project. Tech. rep., The World Bank, 1977."
r56  "Wiens, T B, The Economics of High-yield Agriculture in China: Triple-Cropping at the Baimano Peoples' Commune. The World Bank, Washington DC, 1985."
r57  "World Bank, Tanzania: Appraisal of the Tabora Rural Development Project. Tech. rep., The World Bank, 1977."
r58  "IMSL Inc, LP/PROTRAN - A Problem Solving System for Linear Programming . Tech. rep., IMSL, 1984."
r59  "CDC, PDS/APEX Sample Model Library. Control Data Corporation"
r60  "Bergendorff, H, Glenshaw, P, and Meeraus, A, The Planning of Investment Programs in the Paper Industry. Tech. rep., The World Bank, 1980."
r61  "Ramsey, F P, A Mathematical Theory of Saving. Economics Journal (1928)."
r62  "Murtagh, B A, and Saunders, M A, A Projected Lagrangian Algorithm and its Implementation for Sparse Nonlinear Constraints. Mathematical Programming Study 16 (1982), 84-117."
r63  "Kendrick, D, Caution and Probing in a Macroeconomic Model. Journal of Economic Dynamics and Control 4, 2 (1982)."
r64  "Palmer, K H, A Model Management Framework for Mathematical Programming. John Wiley and Sons, 1984."
r65  "Meeraus, A, and Smeers, Y, Transport Cost Estimates via Linear Programming. The World Bank, 1985."
r66  "Brooke, A, Kendrick, D, and Meeraus, A, GAMS: A User's Guide. The Scientific Press, Redwood City, California, 1988."
r67  "Brooke, A, Drud, A S, and Meeraus, A, Modeling Systems and Nonlinear Programming in a Research Environment. In Ragavan, R, and Rohde, S M, Eds, Computers in Engineering, Vol. III. ACME, 1985."
r68  "Drud, A S, and Rosenborg, A, Dimensioning Water Distribution Networks. Masters thesis, Institute of Mathematical Statistics and Operations Research, Technical University of Denmark, 1973. (in Danish)"
r69  "Fair, R C, Specification, Estimation, and Analysis of Macroeconomic Models. Harvard University Press, Cambridge, Mass, 1984."
r70  "Fourer, R, Gay, D M, and Kernighan, B W, AMPL: A Mathematical Programming Language. Scientific Press, Murray Hill, New Jersey, 1987."
r71  "Kutcher, G P, The Agro-Economic Model, Master Plan for Water Resources Development. Tech. rep., UNDP-EGY-73/024, 1980."
r72  "Wall, T W, Greening, D, and Woolsey, R E D, Solving Complex Chemical Equilibria Using a Geometric-Programming Based Technique. Operations Research 34, 3 (1987)."
r73  "Zenios, S A, Drud, A S, and Mulvey, J, Balancing some large Social Accounting Matrices with Nonlinear Programming. Tech. rep., Department of Civil Engineering, Princeton University, 1986."
r74  "IBM, MPSX/370 Primer. Tech. rep., IBM, 1979."
r75  "Manne, A S, ETA-MACRO: A Model of Energy-Economy Interactions. In Hitch, C J, Ed, Modeling Energy-Economy Interactions: Five Approaches. Resources for the Future, Washington, DC, 1977."
r76  "Condon, T, Dahl, H, and Devarajan, S, Implementing a Computable General equilibrium Model on GAMS - The Cameroon Model. Tech. rep., The World Bank, 1987."
r77  "Teisberg, T J, A Dynamic Programming Model of the U.S. Strategic Petroleum Reserve. Bell Journal of Economics (1981)."
r78  "Rosenbrock, H H, An Automatic Method for finding the Greatest or least value of a function. Computer Journal 3 (1960), 175-184."
r79  "Wright, M H, Numerical Methods for Nonlinearly Constraint Optimization. PhD thesis, Stanford University, 1976."
r80  "Harker, P T, Alternative Models of Spatial Competition. Operations Research 34, 3 (1986), 410-425."
r81  "Le-Si, V, Scandizzo, P L, and Kasnagoklu, H, Turkey Agricultural Sector Model. Tech. rep., The World Bank, 1982."
r82  "Kutcher, G P, and Scandizzo, P L, The Agricultural Economy of Northeast Brazil. The Johns Hopkins University Press, Baltimore and London, 1981."
r83  "Duloy, J H, and O'Mara, G T, Issues of Efficiency and Interdependence in Water Resource Investments: Lessons from the Indus Basin of Pakistan. Tech. rep., The World Bank, 1984."
r84  "Kutcher, G P, Meeraus, A, and O'Mara, G T, Agriculture Sector and Policy Models. The World Bank, 1988."
r85  "Hillier, F S, and Lieberman, G J, Introduction to Operations Research. Holden-Day, San Francisco, 1967."
r86  "Himmelblau, D M, Problem Number 11. In Applied Nonlinear Programming. Mc Graw Hill, New York, 1972."
r87  "Mangasarian, O L, Nonlinear Programming. McGraw Hill, New York, 1973."
r88  "Mitra, P, and Tendulkar, S, Coping with Internal and External Exogenous Shocks: India. Tech. rep., The World Bank, 1986."
r89  "Choypeng, P, Puakpong, P, and Rosenthal, R E, Optimal Ship Routing and Personnel Assignment for Naval Recruitment in Thailand. Interfaces 16, 4 (1986), 356-366."
r90  "Borland, Eureka: The Solver, Borland International, Scotts Valley, California, 1987."
r91  "Thompson, G, and Thor, S, Computational Economics: Economic Modeling with Optimization Software. The Scientific Press, San Francisco, 1991."
r92  "Beauvais, J, Solving the Maximum Queens Chess Problem with OSL. IBM Kingston, EKKNEWS 2 (1991)."
r93  "Mitra, P, Adjustments in Oil Importing Developing Countries: A Comparative Economic Analysis. Cambridge University Press, New York, NY, 1993."
r94  "Dahl, H, Meeraus, A, and Zenios, S A, Some Financial Optimization Models: Risk Management. In Zenios, S A, Ed, Financial Optimization. Cambridge University Press, New York, NY, 1993."
r95  "Kocis, G R, and Grossmann, I E, Relaxation Strategy for the Structural Optimization of Process Flow Sheets. Industrial and Engineering Chemical Research 26, 9 (1987), 1869-1880."
r96  "Morari, M, and Grossmann, I E, Eds, Chemical Engineering Optimization Models with GAMS. Computer Aids for Chemical Engineering Corporation, 1991."
r97  "Yee, T F, and Grossmann, I E, Simultaneous Optimization of Models for Heat Integration - Heat Exchanger Network Synthesis. Computers and Chemical Engineering 14, 10 (1990), 1165-1184."
r98  "Floudas, C A, and Paules IV, G E, A Mixed-Integer Nonlinear Programming Formulation for the Synthesis of Heat Integrated Distillation Sequence. Computers and Chemical Engineering 12, 6 (1988), 531-546."
r99  "Kocis, G R, and Grossmann, I E, Global Optimization of Nonconvex MINLP Problems in Process Synthesis. Industrial and Engineering Chemical Research 27 (1988), 1407-1421."
r100  "Aggarwal, A, and Floudas, C A, Synthesis of General Distillation Sequences: Nonsharp Separation. Computers and Chemical Engineering 14, 6 (1990), 631-653."
r101  "Raman, R, and Grossmann, I E, Relation between MINLP Modeling and Logical Inverence for Chemical Process Synthesis. Computers and Chemical Engineering 15, 2 (1991), 73-84."
r102  "Viswanathan, J, and Grossmann, I E, A Combined Penalty Function and Outer Approximation Method for MINLP Optimization. Computers and Chemical Engineering 14, 7 (1990), 769-782."
r103  "Kocis, G R, and Grossmann, I E, Computational Experience with DICOPT Solving Minlp Problems in Process Synthesis. Computers and Chemical Engineering 13, 3 (1989), 307-315."
r104  "Manne, A S, GAMS/MINOS: Three examples. Tech. rep., Department of Operations Research, Stanford University, 1986."
r105  "Shoven, J, and Whalley, J, Applied G.E. Models. Journal of Economic Literature 22 (1984)."
r106  "Scarf, H, and Hansen, T, The Computation of Economic Equilibria. Yale University Press, 1973."
r107  "Murphy, F H, Sherali, H D, and Soyster, A L, A Mathematical Programming Approach for Determining Oligopolistic Market Equilibrium. Mathematical Programming 24 (1982), 92-106."
r108  "Harker, P T, A Variational Inequality Approach for the Determination of Oligopolistic Market Equilibrium. Mathematical Programming 30 (1984), 105-111."
r109  "Manne, A S, and Richels, R G, Buying Greenhouse Insurance: The Economic Cost of Dioxide Emission Limits. MIT Press Cambridge, 1992."
r110  "Robinson, S, Kilkenny, M, and Hanson, K, The USDA/ERS Computable General Equilibrium (CGE) Model of the United States. Tech. rep., USDA/ERS, 1990."
r111  "Thorpe, S, The Effects of Fuel Economy Standards on Automobile Sales and Average Fuel Efficiency. Tech. rep., Department of Economics, University of Colorado, 1994."
r112  "Boehringer, C, and Rutherford, T F, Carbon taxes with exemptions in an open economy: a general equilibrium analysis of the German tax initiative. Journal of Environmental Economics and Management 32 (2) (1997), 189-203."
r113  "Lopez de Silanes, F, Markusen, J R, and Rutherford, T F, Complementarity and Increasing Returns in Intermediate Inputs: A Theoretical and Applied General-Equilibrium Analysis. Journal of Development Economics 45 (1994), 133-151."
r114  "Perroni, C, and Rutherford, T F, International Trade in Carbon Emission Rights and Basic Materials: General Equilibrium Calculations for 2020. Scandinavian Journal of Economics 95, 3 (1993), 257-278."
r115  "Markusen, J R, and Feenstra, R, Accounting for Growth with New Inputs. Journal of International Economics (1993)."
r116  "Torma, H, and Rutherford, T F, A General Equilibrium Assessment of Finland's grand Tax Reform. Tech. rep., Department of Economics and Management, University of Jyvaskyla, 1992."
r117  "Balard, C L, Fullerton Don, Shoven, J, and Whalley, J, A General Equilibrium Model for Tax Policy Evaluation. University of Chicago Press, 1985."
r118  "Kamiya, K, Computation of Equilibria with Increasing Returns to Scale. Tech. rep., Faculty of Economics, Osaka University, ?."
r119  "Kehoe, T, A Numerical Investigation of the Multiplicity of Equilibria. Mathematical Programming Study 23 (1985), 240-258."
r120  "Manne, A S, and Preckel, P V, North-South Trade, Capital Flows and Economic Growth: An Almost Neoclassical Model. In Syrquin, M, Ed, Economic Structure and Performance: Essays in Honor of Hollis B. Chenery. Academic Press, 1984."
r121  "Miller, M H, and Spencer, J E, The Static Economic Effects of the UK joining the EEC: A General Equilibrium Approach. R.E.Stud, 1975."
r122  "Rutherford, T F, Applied General Equilibrium Modeling with MPSGE as a GAMS Subsystem: An Overview of the Modeling Framework and Syntax. Computational Economics 14 (1999), 1-46."
r123  "Scarf, H, Some Examples of Global Instability of the Competitive Equilibrium. International Economic Review 1 (1960), 157-171."
r124  "Mackinnon, J, A Technique for the Solution of Spatial Equilibrium Models. Journal of Regional Science 16, 3 (1976), 293-307."
r125  "Dantzig, G B, Chapter 26.3. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r126  "Bracken, J, and McCormick, G P, Chapter 7. In Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968, pp. 58-82."
r127  "House, B, Internet Communications."
r128  "Dantzig, G B, Chapter 23.2. In Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r129  "Berna, T, Locke, M, and Westerberg, A W, A New Approach to Optimization of Chemical Processes. American Institute of Chemical Engineers Journal 26, 1 (1980), 37-43."
r130  "Wood, A J, and Wollenberg, B F, Example Problem 4e. In Power Generation, Operation and Control. John Wiley and Sons, 1984, pp. 85-88."
r131  "Wood, A J, and Wollenberg, B F, Example Problem 7b. In Power Generation, Operation and Control. John Wiley and Sons, 1984, p. 202."
r132  "Ferris, M C, Meeraus, A, and Rutherford, T F, Computing Wardropian Equilibria in a Complementarity Framework. Optimization Methods and Software 10 (1999), 669-685."
r133  "Michna, M, and Gdanska, P, Winding Factor of Electrica Machines."
r134  "Ahmad, M, and Kutcher, G P, Irrigation Planning with Environmental Considerations - A Case Study of Pakistans's Indus Basin. Tech. rep., The World Bank, 1992."
r135  "Laguna, M, Applying Robust Optimization to Capacity Expansion of One Location in Telecommunications with Demand Uncertainty. Management Science 44, 11 (1998), 101-110."
r136  "King, A J, Stochastic Programming Problems: Examples from the Literature. In Ermoliev, Y, and Wets, R J, Eds, Numerical Techniques for Stochastic Optimization Problems. Springer Verlag, 1988, pp. 543-567."
r137  "Kall, P, and Wallace, S W, Stochastic Programming. John Wiley and Sons, Chichester, England, 1994."
r138  "Louveaux, F V, and Smeers, Y, Optimal Investments for Electricity Generation: A Stochastic Model and a Test Problem. In Ermoliev, Y, and Wets, R J, Eds, Numerical Techniques for Stochastic Optimization Problems. Springer Verlag, 1988, pp. 445-452."
r139  "Borndoerfer, R, Groetschel, M, and Loebel, A, Alcuins Transportation Problems and Integer Programming. In Butzer, P L, Ed, Charlemagne and His Heritage: 1200 Years of Civilization and Science in Europe. Brepols, Belgium, 1998, pp. 379-409."
r140  "Dyson, Thanassoulis, and Boussofiane, A DEA Tutorial. Warwick Business School"
r141  "Savant, M, Ask Marilyn. Parade, May 23"
r142  "Carlson, R C, and Nemhauser, G L, Scheduling to Minimize Interaction Cost. Operations Research 14 (1966), 52-58."
r143  "Infanger, G, Planning Under Uncertainty - Solving Large-Scale Stochastic Linear Programs."
r144  "Birge, J R, and Louveaux, F V, Introduction to Stochastic Programming. Springer, 1997."
r145  "Gill, P E, Murray, W, and Saunders, M A, GAMS/SNOPT: An SQP Algorithm for Large-Scale Constrained Optimization."
r146  "Siddall, J N, Optimal Engineering Design: Principles and Applications. Marcel Dekker, New York, 1982."
r147  "Deb, K, and Goyal, M, Optimizing Engineering Designs Using a Combined Genetic Search. In Back, T, Ed, Proceedings of the Seventh International Conference on Genetic Algorithms. 1997, pp. 521-528."
r148  "Coello Coello, C A, Treating Constraints as Objectives for Single-Objective Evolutionary Optimization. Engineering Optimization 32 (2000), 275-308."
r149  "Harjunkoski, I, Application of MINLP Methods on a Scheduling Problem in the Paper Converting Industry. PhD thesis, Abo Akademi University, 1997."
r150  "Floudas, C A, Pardalos, P M, Adjiman, C S, Esposito, W R, Gumus, Z H, Harding, S T, Klepeis, J L, Meyer, C A, and Schweiger, C A, Handbook of Test Problems in Local and Global Optimization. Kluwer Academic Publishers, 1999."
r151  "Westerlund, T, Petterson, F, and Grossmann, I E, Optimization of Pump Configurations as a MINLP Problem. Computers and Chemical Engineering 18, 9 (1994), 845-858."
r152  "Sandgren, E, Nonlinear Integer and Discrete Programming in Mechanical Design Optimization. Journal of Mechanical Design, Trans. ASME 112 (1990), 223-229."
r153  "Voss, S, and Woodruff, D L, Introduction to Computational Optimization Models for Production Planning in a Supply Chain."
r154  "Dantzig, G B, Fulkerson, and Johnson, Solution of a Large-Scale Traveling-Salesman Problem. Operations Research 2 (1954), 393-410."
r155  "Haverly, C A, Studies of the Behavior of Recursion for the Pooling Problem. ACM SIGMAP Bull 25 (1978), 19-28."
r156  "Adhya, N, Tawarmalani, M, and Sahinidis, N, A Lagrangian Approach to the Pooling Problem. Industrial and Engineering Chemical Research 38 (1999), 1956-1972."
r157  "de Wolf, D, and Smeers, Y, The Gas Transmission Problem Solved by and Extension of the Simplex Algorithm. Management Science 46, 11 (2000), 1454-1465."
r158  "Bosch, R A, Peacable Coexisting Armies of Queens. OPTIMA MPS Newsletter, 62 (1999), 6-9."
r159  "Schrijver, A, Minimum Circulation of Railway Stock. CWI Quarterly 3 (1993), 205-217."
r160  "Bussieck, M R, Optimal Lines in Public Rail Transport. PhD thesis, TU Braunschweig, 1998."
r161  "Bussieck, M R, Kreuzer, P, and Zimmermann, U T, Optimal Lines for Railway Systems. European Journal of Operation Research 96, 1 (1996), 54-63."
r162  "Claessens, M T, van Dijk, N M, and Zwaneveld, P J, Cost Optimal Allocation of Rail Passenger Lines. European Journal Operation Research 110, 3 (1998), 474-489."
r163  "Lawler, E L, Lenstra, J K, Rinnoy Kan, A H G, and Shmoys, D B, Eds, The Traveling Salesman Problem, A Guided Tour of Combinatorial Optimization. Wiley, 1985."
r164  "Aronofsky, J S, Dutton, J M, and Tayyabkhan, M T, Managerial Planning with Linear Programming. John Wiley and Sons, New York, 1978."
r165  "Wagner, H M, Military Manpower Planning Example. In Principles of Operations Research with Applications to Managerial Decisions, Second Edition. Prentice-Hall, 1975, p. 66."
r166  "Rowse, Mackinnon, J, Samuelson, and von Thunen, General Equilibrium Variant of the von Thunen Model."
r167  "Jain, V, and Grossmann, I E, Cyclic Scheduling of Continuous Parallel Units with Decaying Performance. American Institute of Chemical Engineers Journal 44, 7 (1998), 1623-1636."
r168  "Edgar, T F, Himmelblau, D M, and Lasdon, L S, Optimization of Chemical Processes. McGraw Hill, Boston, 2001."
r169  "Silver, E A, and Moon, I, A Fast Heuristic for Minimizing Total Average Cycle Stock Subject to Practical Constraints. Journal of the Operational Research Society 50 (1999), 789-796."
r170  "Robinson, S, Cattaneo, A, and El-Said, M, Updating and Estimating a Social Accounting Matrix Using Cross Entropy Methods. Economic System Research 13, 1 (2001)."
r171  "Golan, A, Judge, G, and Miller, D, Maximum Entropy Econometrics. John Wiley and Sons, 1996."
r172  "Rutherford, T F, GEMTAP: A General Equilibrium Model for Tax Policy."
r173  "Chenery, H B, and Westphal, L E, Economies of Scale and Investment Over Time. In Chenery, H B, Ed, Structural Change and Development Policy. Oxford University Press, New York and Oxford, 1979."
r174  "Ragavan, R, and Rohde, S M, Eds, Computers in Engineering, Vol. III, 1985."
r175  "Back, T, Ed, Proceedings of the Seventh International Conference on Genetic Algorithms, 1997."
r176  "Wood, A J, and Wollenberg, B F, Power Generation, Operation and Control. John Wiley and Sons, 1984."
r177  "Zenios, S A, Ed, Financial Optimization. Cambridge University Press, New York, NY, 1993."
r178  "Chenery, H B, Robinson, S, and Syrquin, M, Eds, Industrialization and Growth: A Comparative Study. Oxford University Press, London, 1986."
r179  "Ermoliev, Y, and Wets, R J, Eds, Numerical Techniques for Stochastic Optimization Problems. Springer Verlag, 1988."
r180  "Dantzig, G B, Linear Programming and Extensions. Princeton University Press, Princeton, New Jersey, 1963."
r181  "Bracken, J, and McCormick, G P, Selected Applications of Nonlinear Programming. John Wiley and Sons, New York, 1968."
r182  "Syrquin, M, Ed, Economic Structure and Performance: Essays in Honor of Hollis B. Chenery. Academic Press, 1984."
r183  "Himmelblau, D M, Applied Nonlinear Programming. Mc Graw Hill, New York, 1972."
r184  "Turvey, R, and Anderson, D, Electricity Economics: Essays and Case Studies. Johns Hopkins University Press, Baltimore and London, 1977."
r185  "Chenery, H B, Ed, Studies of Development Planning. Harvard University Press, 1971."
r186  "Hallet, A J H, Ed, Applied Decision Analysis and Economic Behavior. Kluwer and Nijhoff, Boston and The Hague, 1984."
r187  "Chenery, H B, Ed, Structural Change and Development Policy. Oxford University Press, New York and Oxford, 1979."
r188  "Manne, A S, and Markowitz, H M, Eds, Studies in Process Analysis. John Wiley and Sons, New York and London, 1963."
r189  "Goreaux, L M, and Manne, A S, Eds, Multi-level Planning: Case Studies in Mexico. North-Holland, Amsterdam, 1973."
r190  "Hitch, C J, Ed, Modeling Energy-Economy Interactions: Five Approaches. Resources for the Future, Washington, DC, 1977."
r191  "Kindleberger, C P, and di Tella, G, Eds, Economics in the Long View, Essays in the Honor of W W Rostow. Macmillan, London, 1982."
r192  "Wagner, H M, Principles of Operations Research with Applications to Managerial Decisions, Second Edition. Prentice-Hall, 1975."
r193  "Harjunkoski, I, Westerlund, T, Porn, R, and Skrifvars, H, Different Transformations for Solving Non-Convex Trim Loss Problems by MINLP. European Journal of Operational Research 105, 3 (1998), 594-603."
r194  "Dolan, E D, and More, J J, Benchmarking Optimization Software with COPS. Tech. rep., Mathematics and Computer Science Division, 2000."
r195  "Graham, R L, The Largest Small Hexagon. J. Combin. Th. 18 (1975), 165-170."
r196  "Gay, D M, AMPL Models."
r197  "Morris, J R, Deaven, D M, and Ho, K M, Genetic Algorithm Energy Minimization for Point Charges on a Sphere. Phys. Rev. B. 53 (1996), R1740-R1743."
r198  "Saff, E B, and Kuijlaars, A, Distributing Many Points on the Sphere. Math. Intelligencer 19 (1997), 5-11."
r199  "Cesari, L, Optimization - Theory and Applications. Springer Verlag, 1983."
r200  "Anitescu, M, and Serban, R, A Sparse Superlinearly Convergent SQP with Applications to Two-Dimensional Shape Optimization. Tech. rep., Argonne National Laboratory, 1998."
r201  "Box, G E P, Hunter, W G, MacGregor, J F, and Erjavec, J, Some Problems Associated with the Analysis of Multiresponse Data. Technometrics 15 (1973), 33-51."
r202  "Tjoa, I B, and Biegler, L T, Simultaneous Solution and Optimization Strategies for Parameter Estimation of Differential-Algebraic Equations Systems. Ind. Eng. Chem. Res. 30 (1991), 376-385."
r203  "Averick, B M, Carter, R G, More, J J, and Xue, G L, The MINPACK-2 Test Problem Collection. Tech. rep., Mathematics and Computer Science Division, Argonne National Laboratory, 1992."
r204  "Ascher, U M, Mattheij, R M M, and Russell, R D, Numerical Solution of Boundary Value Problems for Ordinary Differential Equations. SIAM, 1995."
r205  "Rothschild, B J, Sharov, A F, and Bondarenko, A S, Estimating Growth and Mortality in Stage-Structured Populations. Journal of Plankton Research 19 (1997), 1913-1928."
r206  "Friedman, A, Free Boundary Problems in Science and Technology. Notices Amer. Math. Soc. 47 (2000), 854-861."
r207  "Vanderbei, R, Nonlinear Optimization Models."
r208  "Betts, J, Eldersveld, S, and Huffman, W, Sparse Nonlinear Programming Test Problems. Tech. rep., Boeing Computer Services, 1993."
r209  "Bryson, A E, and Ho, Y, Applied Optimal Control: Optimization, Estimation, and Control. John Wiley and Sons, 1975."
r210  "Bryson, A E, Dynamic Optimization. Addison Wesley, 1999."
r211  "Bulirsch, R, Nerz, E, Pesch, H J, and von Stryk, O, Combining Direct and Indirect Methods in Nonlinear Optimal Control: Range Maximization of a Hang Glider. In Bulirsch, R, Ed, Optimal Control. Birkhauser Verlag, 1993, pp. 273-288."
r212  "Maria, G, An Adaptive Strategy for Solving Kinetic Model Concomitant Estimation - Reduction Problems. Can. J. Chem. Eng. 67 (1989), 825."
r213  "von Stryk, O, User's Guide for DIRCOL (Version 2.1): A Direct Collocation Method for the Numerical Solution of Optimal Control Problems. Tech. rep., Technische Universitat Munchen, 1999."
r214  "Glowinski, R, Numerical Methods for Nonlinear Variational Problems. Springer Verlag, 1984."
r215  "Capriz, G, and Cimatti, G, Free Boundary Problems in the Theory of Hydrodynamic Lubrication: A Survey. In Fasano, A, and Primicerio, M, Eds, Research Notes in Mathematics. Pitman, 1983, pp. 613-635."
r216  "Bulirsch, R, Ed, Optimal Control. Birkhauser Verlag, 1993."
r217  "Fasano, A, and Primicerio, M, Eds, Research Notes in Mathematics. Pitman, 1983."
r218  "Martello, S, and Toth, P, Knapsack Problems: Algorithms and Computer Implementations. John Wiley and Sons, Chichester, 1990."
r219  "Guignard, M, and Rosenwein, M, An Improved Dual-Based Algorthm for the Generalized Assignment Problem. Operations Research 37 (1989), 658-663."
r220  "Dudeney, H E, Amusements in Mathematics. Dover, New York, 1970."
r221  "GAMS Development Corporation, Modeling Tool Box."
r222  "GAMS Development Corporation, Formulation and Language Example."
r223  "Kalvelagen, E, Model Building with GAMS. forthcoming"
r224  "de Wetering, A V, private communication."
r225  "Gardner, M, The Colossal Book of Mathematics. WV Norton, New York, NY, 2001."
r226  "Butzer, P L, Ed, Charlemagne and His Heritage: 1200 Years of Civilization and Science in Europe. Brepols, Belgium, 1998."
r227  "Bollapragada, S, Cheng, H, Phillips, M, and Garbiras, M, NBC's Optimization Systems Increase Its Revenues and Productivity. Interfaces 31, 1 (2002)."
r228  "Bollapragada, S, Bussieck, M R, and Mallik, S, Scheduling Commercial Videotapes in Broadcast Television, 2003."
r229  "Gutierrez, R A, and Sahinidis, N, A Lagrangian Approach to the Pooling Problem. Interantional J Production Research 34 (1996), 797-818."
r230  "Gunasekaran, A, Goyal, S K, Martikainen T, and Yli-Olli, P, Equipment Selection Problems in just-in-time Manufacturing Systems. Journal of the Operational Research Society 44 (1993), 345-353."
r231  "Konno, H, and Kuno, T, Linear multiplicative programming. Mathematical Programming 56 (1992), 51-64."
r232  "Tawarmalani, M, and Sahinidis, N, Convexification and Global Optimization in Continuous and Mixed-Integer Nonlinear Programming: Theory, Algorithms, Software, and Applications. Kluwer, 2002."
r233  "Thoai, N V, A global optimization approach for solving convex multiplicative programming problems. Journal of Global Optimization 1 (1991), 341-357."
r234  "Benson, H P, and Boger, G M, Multiplicative programming problems: Analysis and efficient point search heuristic. Journal of Optimization Theory and Applications 94 (1997), 487-510."
r235  "Haverly, C A, Behaviour of recursion model - More studies. ACM SIGMAP Bulletin 26 (1979), 22-28."
r236  "Foulds, L R, Haugland, D, and Jornsten, K, A bilinear approach to the pooling problem. Optimization 24 (1992), 165-180."
r237  "Ben-Tal, A, Eiger, G, and Gershovitz, V, Global Minimization by Reducing the Duality Gap. Mathematical Programming 63 (1994), 193-212."
r238  "Audet, C, Brimberg, J, Hansen, P, and Mladenovic, N, Pooling problem: Alternate formulations and solution methods. Tech. rep., Les Cashiers Du GERAD G-2000-23, Montreal, 2000."
r239  "Adhya, N, Tawarmalani, M, and Sahinidis, N, Global optimization of the pooling problem. Industrial and Engineering Chemistry 38 (1999), 1956--1972."
r240  "Dirkse, S P, and Ferris, M C, MCPLIB: A Collection of Nonlinear Mixed Complementarity Problems. Optimization Methods and Software 5 (1995), 319-345."
r241  "Harker, P T, Accelerating the Convergence of the Diagonalization and Projection Algorithms for Finite--Dimensional Variational Inequalities. Math. Prog. 41 (1988), 29-59."
r242  "Pinter, J D, LGO - A Model Development System for Continuous Global Optimization. User's Guide. (Revised edition). Pinter Consulting Services, Halifax, NS Canada, 2003."
r243  "Mathematica, MathOptimizer - An Advanced Modeling and Optimization System for Mathematica Users. http://www.wolfram.com/products/applications/mathoptimizer/"
r244  "Pinter, J D, Global Optimization in Action. Kluwer Acadameic Publishers, Dordrecht/Boston/London, 1996."
r245  "Pinter, J D, Computational Global Optimization in Nonlinear Systems. Lionheart Publishing, Atlanta, GA, 2001."
r246  "Trefethen, N, The Hundred-dollar, Hundred-digit Challenge Problems. SIAM News, January - February 2002, page 3"
r247  "Stinstra, E, den Hertog, D, Stehouwer, H P, and Vestjens, A, Constrained Maximin Designs for Computer Experiments. Technometrics (under revision) (2002)."
r248  "Chlond, M J, Daniel, R C, and Heipcke, S, Fiveleapers a-leaping. http://www.chlond.demon.co.uk/leapers/"
r249  "Gueret, C, Prins, C, and Sevaux, M, Applications of Optimization with Xpress-MP, Translated and revised by Susanne Heipcke. Dash Optimization, 2002."
r250  "Hock, W, and Schittkowski, K, Test Examples for Nonlinear Programming Codes, Lecture Notes in Economics and Mathematical Systems. Springer Verlag, 1981."
r251  "Floudas, C A, and Pardalos, P M, Eds, Frontiers in Global Optimization. Kluwer Academic Publishers, 2003."
r252  "Kallrath, J, Exact Computation of Global Minima of a Nonconvex Portfolio Optimization Problem. In Floudas, C A, and Pardalos, P M, Eds, Frontiers in Global Optimization. Kluwer Academic Publishers, 2003."
r253  "Andersen, E, MOSEK Optimization Tools Manual, online at http://www.mosek.com/documentation.html."
r254  "Bosch, R A, Mindsharpener. Optima MP 70 (2003), 8-9."
r255  "Vanderbei, R, Nonlinear Optimization Models (AMPL), See http://www.princeton.edu/~rvdb/ampl/nlmodels/."
r256  "Hosoe, N, Gasawa, K, and Hashimoto, H, Handbook of Computible General Equilibrium Modeling. University of Tokyo Press, Tokyo, Japan, 2004."
r257  "Ortega, F, and Wolsey, L, A branch-and-cut algorithm for the single-commodity, uncapacitated, fixed-charge network flow problem. Networks 41 (3) (2003), 143-158."
r258  "Bussieck, M R, and Ni, H, Technical Note: Solving the Steiner Tree Problem with GAMS Branch-and-Cut Facility. Tech. rep., GAMS Development Corporation, 2003."
r259  "Brimberg, J, Hansen, P, Lih, K, Mladenovic, N, and Breton, M, An Oil Pipeline Design Problem. Operations Research 51 (2) (2003), 228-239."
r260  "Bussieck, M R, and Ni, H, Technical Note: Solving an Oil Pipeline Design Problem with the GAMS Branch-and-Cut Facility. Tech. rep., GAMS Development Corporation, 2003."
r261  "Petersen, C C, Computational experience with variants of the Balas algorithm applied to the selection of R&D projects. Management Science 13 (9) (1967), 736-750."
r262  "Linderoth, J, IE418 Lecture Notes - Lecture #19, 2003. Lehigh University, http://www.lehigh.edu/~jtl3/teaching/ie418/lecture19.pdf"
r263  "Beasley, J E, OR-Library: distributing test problems by electronic mail. Journal of the Operational Research Society 41 (11) (1990), 1069-1072."
r264  "Neumaier, A, and Shcherbina, O, Safe Bounds in Linear and Mixed-Integer Programming. Mathematical Programming A to appear, (2003)."
r265  "Gilmore, P C, and Gomory, R E, A Linear Programming Approach to the Cutting Stock Problem, {Part I}. Operations Research 9 (1961), 849--859."
r266  "Gilmore, P C, and Gomory, R E, A Linear Programming Approach to the Cutting Stock Problem, {Part II}. Operations Research 11 (1963), 863--888."
r267  "Burkard, R E, Karisch, S E, and Rendl, F, QAPLIB - A Quadratic Assignment Problem Library. Journal of Global Optimization 10 (1997), 391--403."
r268  "Somwaru, A, Problem contribution, ERS, US Department of Agriculture, Washington, DC."
r269  "Doufherty, D, and Robbins, A, SED and AWK. O'Reilly & Associates, Sebastobol, 1997."
r270  "Juenger, M, Reinelt, G, and Thienel, S, Optimal and Probably Good Solutions for the Symmetric Traveling Salesman Problem. Zeitschrift fuer Operations Research 40 (1994), 183--217."
r271  "Sloane, N J A, The On-Line Encyclopedia of Integer Sequences; Sequence A030169. http://www.research.att.com/projects/OEIS?Anum=A030169"
r272  "Ogura, A, Post-Gaussian variational method for quantum anharmonic oscillator, 1999. Laboratory of Physics, College of Science and Technology, Nihon University,arXiv:physics/9905056 v1 28 May 1999"
r273  "Chen, C H, and Chou, C Y, Determining the Optimum Process Mean under a Beta Distribution. Journal of the Chinese Institute of Industrial Engineers 18 (3) (2003), 27--32."
r274  "Phillips, M D, and Cho, B R, Determining the Optimum Process Mean under a Beta Distribution. A Nonlinear model for determining the most economic process mean under a beta distribution 7 (2000), 61--74."
r275  "Kotz, J, and Balakrishnan, N, Continuous Univariate Distributions, Volumes I and II, 2nd Ed.. John Wiley and Sons, 1994."
r276  "Cox, D R, and Snell, E J, Applied Statistics: Principles and Examples. London: Chapman and Hall, 1981."
r277  "Tierney, L, XLISP-STAT, A Statistical Environment Based on the XLISP Language (Version 2.0), Number 528. Tech. rep., University of Minnesota, School of Statistics, 1989."
r278  "Rutherford, T F, Tarr, D, and Shepotylo, O, Poverty Effects of Russia's WTO Accession: modeling 'real' households and endogenous productivity effects. Tech. rep., The World Bank, September 2004."
r279  "Wright, S I, Le, Q H, Schoen, D J, and Bureau T E, Population Dynamics of an Ac-like Transposable Element in Self- and Cross-Pollinating Arabidopsis. Genetics 158 (2001), 1279-1288."
r280  "O'Brochta, D, Private Communications, 2004."
r281  "Meeraus, W H, A Combined Fieldwork and Laboratory Investigation into the Behaviour of the Herves Transposable Element. Masters thesis, London School of Hygiene and Tropical Medicine, 2004."
r282  "Meneses, C N, Lu, Z, Oliveira, C A S, and Pardalos, P M, Optimal Solutions for the Closest-String Problem via Integer Programming. INFORMS Journal on Computing 16, 4 (2004), 419-429."
r283  "Cox, L H, Kelly, J P, and Patil, R J, Computational Aspects of Controlled Tabular Adjustements: Algorithms and Analaysis. In Golden, B L, Raghavan, S, and Wasil, E A, Eds, The Next Wave in Computing, Optimization, and Decision Technologies. Springer Verla"
r284  "Garver, L L, Power Scheduling by Integer Programming, Tariff-Rates-Power-Generation-Problem. IEEE Trans. Power Apparatus and Systems 81 (1963), 730-735."
r285  "Mavrotas, G, Effective implementation of the eps-constraint method in Multi-Objective Mathematical Programming problems. Applied Mathematics and Computation 213, 2 (2009), 455--465."
r286  "Kucherenko, S, Belotti, P, Liberti, L, and Maculan, N, New formulations for the Kissing Number Problem. Tech. rep., LIX Ecole Polytechnique, Palaiseau F-91128, France, 2006."
r287  "Klingman, D, Napier, A, and Stutz, J, NETGEN: A program for generating large scale capacitated assignment, transportation, and minimum cost flow networks. Management Science 20 (1974), 814-820."
r288  "Clark, R H, Kennington, L, Meyer, R R, and Ramamurti, M, Generalized Networks: Parallel Algorithms and an Empirical Analysis. ORSA Journal on Computing 4, 2 (1992), 132-145."
r289  "Panton, D M, and Elbers, A W, Mission Planning for Synthetic Aperture Radar Surveillance. Interfaces 29, 2 (1999), 73-88."
r290  "Bosch, R A, Monochromatic Squares. Optima MP 71 (2004), 6-7."
r291  "ILOG, CPLEX 11 User's Manual, 2007."
r292  "Dantzig, G B, and Wolfe, P, Decomposition principle for linear programs. Operations Research 8 (1960), 101-111."
r293  "Bertsekas, D P, and Tsitsiklis, J N, Parallel and distributed computation: numerical methods. Prentice-Hall, Inc., Upper Saddle River, NJ, USA, 1989."
r294  "Florios, K, and Skouras, S, A note on exact computation of max weighted score estimators by mixed integer programming. Tech. rep., National Technical University of Athens and Athens University of Economics and Business, 2007."
r295  "Horowitz, J L, Semiparametric estimation of a work-trip mode choice model. Journal of Econometrics 58, 1-2 (1993), 49-70."
r296  "Vecchietti, A, LogMIP User's Manual, 2007. http://www.logmip.ceride.gov.ar/eng/documentation/logmip_manual.pdf"
r297  "Raman, R, and Grossmann, I E, Modeling and Computational Techniques for Logic Based Integer Programming. Computers and Chemical Engineering 18, 7 (1994), 563-578."
r298  "Turkay M., and Grossmann, I E, Logic-Based Algorithms for the Optimal Synthesis of Process Networks. Computers and Chemical Engineering 20, 8 (1996), 959-978."
r299  "Goemans M.X., and Williamson, D P, Improved Approximation Algorithms for Maximum Cut and Satisfiability Problems Using Semidefinite Programming. Journal of the ACM 42 (1995), 1115-1145."
r300  "Wiegele A., Biq Mac Library - Binary quadratic and Max cut Library."
r301  "Plateau M.C., Reformulations quadratiques convexes pour la programmation quadratique en variables 0-1. PhD thesis, Conservatoire National des Arts et Metiers, CEDRIC, 2006."
r302  "Guignard, M, Extension to Plateau Convexification Method for Nonconvex Quadratic 0-1 Programs. Tech. rep., The Wharton School, 2008."
r303  "Rebennack, S, Kallrath, J, and Pardalos, P M, Energy Portfolio Optimization for Electric Utilities: Case Study for Germany. In Bjorndal, E, Bjorndal, M, Pardalos, P M, and Ronnqvist, M, Eds, Energy, Natural Resources and Environmental Economics. Springer,"
r304  "H. Heitsch, W. Roemisch, and C. Strugarek, Stability of Multistage Stochastic Programs. SIAM Journal on Optimization 17 (2006), 511-525."
r305  "Miller, C E, Tucker, A W, and Zemlin, R A, Integer Programming Formulation of Traveling Salesman Problems. J. ACM 7, 4 (1960), 326-329."
r306  "Kallrath, J, Combined Strategic Design and Operative Planning in the Process Industry, 2009. Submitted to Computers \& Chemical Engineering"
r307  "Rebennack, S, Kallrath, J, and Pardalos, P M, Optimal Storage Design for a Multi-Product Plant: A Non-Convex MINLP Formulation. Tech. rep., University of Florida, 2009. Submitted to Computers and Chemical Engineering"
r308  "Toczek, J, Relief Mission. ORMS Today 37, 4 (2010), 14."
r309  "Takayama, T, and Judge, G G, Spatial Equilibrium and Quadratic Programming. Journal of Farm Economics 46, 1 (1964), 67-93."
r310  "Hieu, P S, Policy option to promote the wood-processing industry in northern Vietnam. PhD thesis, The University of Queensland, Australia, 2011."
r311  "Pochet, Y, and Wolsey, L A, Production Planning by Mixed Integer Programming (Springer Series in Operations Research and Financial Engineering). Springer-Verlag New York, Inc., 2006."
r312  "Pereira, M V F, and Pinto, L M V G, Stochastic optimization of a multireservoir hydroelectric system: A decomposition approach. Water Resources Research 21, 6 (1985), 779-792."
r313  "Pereira, M V F, and Pinto, L M V G, Multi-stage stochastic optimization applied to energy planning. Mathematical Programming 52 (1991), 359-375."
r314  "Hashimoto, H, Hamada, K, and Hosoe, N, A Numerical Approachto the Contract Theory: The Case of Adverse Selection. Tech. rep., National Graduate Institute for Policy Studies, 2012."
r315  "Itoh, H, A Course in Contract Theory. Yuhikaku, Tokyo, 2003."
r316  "Mitsos, A, Global Optimization of Semi-Infinite Programs via Restriction of the Right Hand Side. Optimization 60, 7 (2010)."
r317  "Rasmussen K.M., Finding Optimal Breakpoints when linearizing a power utility function."
r318  "Phan, S H, and Harrison, S, A Review of the Formulation and Application of the Spatial Equilibrium Models to Analyze Policy. Journal of Forestry Research 22, 4 (2011)."
r319  "Miller, R E, and Blair, P D, Input-Output Analysis: Foundations and Extensions. Cambridge University Press, New York, 2009."
r320  "Lobo, M S, Vandenberghe, L, Boyd, S, and Lebret, H, Applications of Second Order Cone Programming. Linear Algebra and its Applications, Special Issue on Linear Algebra in Control, Signals and Image Processing. 284 (November, 1998)."
r321  "Gunluk, O, and Linderoth, J T, Perspective Relaxation of Mixed Integer Nonlinear Programs with Indicator Variables. Mathematical Programming 104 (2010), 183-206."
r322  "Hesamzadeh, M R, and Biggar, D R, Computation of extremal-nash equilibria in a wholesale power market using a single-stage MILP. IEEE Transactions on Power Systems 27, 3 (2012), 1706--1707."
r323  "Olubode-Awosola, O O, van Schalkwyk H D, and Jooste, A, Mathematical modeling of the South African land redistribution for development policy. Journal of Policy Modeling 30, 5 (2008), 841--855."
r324  "Olubode-Awosola, O O, Farm-Level Resource Use and Output Supply Response: A Free State Case Study. PhD thesis, University of the Free State, South Africa, 2006."
r325  "Mavrotas, G, and Florios, K, AUGMECON2:A novel version of the eps-constraint method for finding the exact Pareto set in Multi-Objective Integer Programming problems. Tech. rep., School of Chemical Engineering, National Technical University of Athens, 2012"
/
$onempty
set ro(r) overflow references /
r283  "g, 2005, pp. 45-59."
r303  " 2010, pp. 221-246."
r325  "."
/
$offempty
set cr(r,r) cross references /
r66.(r2)
r174.(r67)
r175.(r147)
r176.(r130,r131)
r177.(r94)
r178.(r38)
r179.(r136,r138)
r180.(r1,r3,r4,r5,r6,r7,r8,r9,r125,r128)
r181.(r17,r18,r19,r20,r21,r22,r23,r24,r25,r26,r126)
r182.(r120)
r183.(r35,r86)
r184.(r54)
r185.(r42)
r186.(r39)
r187.(r32,r33,r173)
r188.(r29)
r189.(r34)
r190.(r75)
r191.(r37)
r192.(r165)
r216.(r211)
r217.(r215)
r226.(r139)
r251.(r252)
/
set cath(ath) credit authors /
"GAMS Model Library"
"Handbook of Test Problems"
/
set athf(ath,r) first author /
"Adhya, N".(r156,r239)
"Aggarwal, A".(r100)
"Ahmad, M".(r134)
"Andersen, E".(r253)
"Anitescu, M".(r200)
"ARCNET".(r11)
"Aronofsky, J S".(r164)
"Ascher, U M".(r204)
"Audet, C".(r238)
"Averick, B M".(r203)
"Back, T".(r175)
"Balard, C L".(r117)
"Beasley, J E".(r263)
"Beauvais, J".(r92)
"Ben-Tal, A".(r237)
"Benson, H P".(r234)
"Bergendorff, H".(r60)
"Berna, T".(r129)
"Bertsekas, D P".(r293)
"Betts, J".(r208)
"Birge, J R".(r144)
"Blitzer, C".(r47)
"Boehringer, C".(r112)
"Bollapragada, S".(r227,r228)
"Borland".(r90)
"Borndoerfer, R".(r139)
"Bosch, R A".(r158,r254,r290)
"Box, G E P".(r201)
"Bracken, J".(r181,r18,r126,r26,r25,r24,r23,r22,r20,r19,r17,r21)
"Brimberg, J".(r259)
"Brooke, A".(r67,r66)
"Brown, M".(r30)
"Bryson, A E".(r210,r209)
"Bulirsch, R".(r216,r211)
"Burkard, R E".(r267)
"Bussieck, M R".(r160,r161,r258,r260)
"Butzer, P L".(r226)
"Capriz, G".(r215)
"Carlson, R C".(r142)
"CDC".(r50,r10,r59)
"Cesari, L".(r199)
"Chakravarty, S".(r43)
"Chen, C H".(r273)
"Chenery, H B".(r178,r185,r187,r33,r173,r32)
"Chlond, M J".(r248)
"Choksi, A M".(r15)
"Choypeng, P".(r89)
"Claessens, M T".(r162)
"Clark, R H".(r288)
"Coello Coello, C A".(r148)
"Condon, T".(r76)
"Cox, D R".(r276)
"Cox, L H".(r283)
"Dahl, H".(r94)
"Dammert, A".(r45)
"Dantzig, G B".(r154,r180,r128,r9,r8,r7,r6,r5,r4,r3,r1,r125,r292)
"Day, R E".(r13)
"de Wetering, A V".(r224)
"de Wolf, D".(r157)
"Deb, K".(r147)
"Dirkse, S P".(r240)
"Dolan, E D".(r194)
"Doufherty, D".(r269)
"Drud, A S".(r68)
"Dudeney, H E".(r220)
"Duloy, J H".(r83)
"Dyson".(r140)
"Edgar, T F".(r168)
"Ellison, E F D".(r12)
"Ermoliev, Y".(r179)
"Fair, R C".(r69)
"Fasano, A".(r217)
"Ferris, M C".(r132)
"Florios, K".(r294)
"Floudas, C A".(r98,r150,r251)
"Foulds, L R".(r236)
"Fourer, R".(r70,r36)
"Friedman, A".(r206)
"GAMS Development Corporation".(r221,r222)
"Gardner, M".(r225)
"Garver, L L".(r284)
"Gay, D M".(r196)
"Gill, P E".(r145)
"Gilmore, P C".(r265,r266)
"Glowinski, R".(r214)
"Goemans M.X.".(r299)
"Golan, A".(r171)
"Goreaux, L M".(r189)
"Graham, R L".(r195)
"Gueret, C".(r249)
"Guignard, M".(r219,r302)
"Gunasekaran, A".(r230)
"Gunluk, O".(r321)
"Gutierrez, R A".(r229)
"H. Heitsch".(r304)
"Hallet, A J H".(r186)
"Harjunkoski, I".(r193,r149)
"Harker, P T".(r108,r80,r241)
"Hashimoto, H".(r314)
"Haverly, C A".(r155,r235)
"Hesamzadeh, M R".(r322)
"Hieu, P S".(r310)
"Hillier, F S".(r85)
"Himmelblau, D M".(r183,r86,r35)
"Hitch, C J".(r190)
"Hock, W".(r250)
"Horowitz, J L".(r295)
"Hosoe, N".(r256)
"House, B".(r127)
"Husain, T".(r49)
"IBM".(r74)
"ILOG".(r291)
"IMSL Inc".(r58)
"Infanger, G".(r143)
"Itoh, H".(r315)
"Jain, V".(r167)
"Juenger, M".(r270)
"Kall, P".(r137)
"Kallrath, J".(r252,r306)
"Kalvelagen, E".(r223)
"Kamiya, K".(r118)
"Kehoe, T".(r119)
"Kendrick, D".(r63,r31,r16,r37,r42,r39)
"Kindleberger, C P".(r191)
"King, A J".(r136)
"Klingman, D".(r287)
"Kocis, G R".(r103,r99,r95)
"Konno, H".(r231)
"Kotz, J".(r275)
"Kucherenko, S".(r286)
"Kutcher, G P".(r84,r82,r71)
"Laguna, M".(r135)
"Lawler, E L".(r163)
"Le-Si, V".(r81)
"Lewis, J".(r38)
"Linderoth, J".(r262)
"Lobo, M S".(r320)
"Lopez de Silanes, F".(r113)
"Louveaux, F V".(r138)
"Mackinnon, J".(r124)
"Mangasarian, O L".(r87)
"Manne, A S".(r104,r120,r109,r53,r188,r34,r75,r52,r29)
"Maria, G".(r212)
"Markusen, J R".(r115)
"Martello, S".(r218)
"Mathematica".(r243)
"Mavrotas, G".(r285,r325)
"Meeraus, A".(r65)
"Meeraus, W H".(r281)
"Melton, J W".(r46)
"Meneses, C N".(r282)
"Mennes, L B M".(r44)
"Michna, M".(r133)
"Miller, C E".(r305)
"Miller, M H".(r121)
"Miller, R E".(r319)
"Mitra, P".(r93,r88)
"Mitsos, A".(r316)
"Morari, M".(r96)
"Morris, J R".(r197)
"Murphy, F H".(r107)
"Murtagh, B A".(r62)
"Neumaier, A".(r264)
"Norton, R D".(r40)
"O'Brochta, D".(r280)
"Ogura, A".(r272)
"Olubode-Awosola, O O".(r323,r324)
"Ortega, F".(r257)
"Palmer, K H".(r64)
"Panton, D M".(r289)
"Pereira, M V F".(r312,r313)
"Perroni, C".(r114)
"Petersen, C C".(r261)
"Phan, S H".(r318)
"Phillips, M D".(r274)
"Pindyck, R S".(r27)
"Pinter, J D".(r242,r244,r245)
"Plateau M.C.".(r301)
"Pochet, Y".(r311)
"Ragavan, R".(r174)
"Raman, R".(r101,r297)
"Ramsey, F P".(r61)
"Rasmussen K.M.".(r317)
"Rebennack, S".(r303,r307)
"Robinson, S".(r110,r170)
"Rosenbrock, H H".(r78)
"Rosenthal, R E".(r2)
"Rothschild, B J".(r205)
"Rowse".(r166)
"Rutherford, T F".(r122,r172,r278)
"Saff, E B".(r198)
"Sandgren, E".(r152)
"Savant, M".(r141)
"Scarf, H".(r123,r106)
"Schrijver, A".(r159)
"Shoven, J".(r105)
"Siddall, J N".(r146)
"Silver, E A".(r169)
"Sloane, N J A".(r271)
"Somwaru, A".(r268)
"Stinstra, E".(r247)
"Suh, J S".(r48)
"Syrquin, M".(r182)
"Takayama, T".(r309)
"Tawarmalani, M".(r232)
"Teisberg, T J".(r77)
"Thoai, N V".(r233)
"Thompson, G".(r91)
"Thorpe, S".(r111)
"Tierney, L".(r277)
"Tjoa, I B".(r202)
"Toczek, J".(r308)
"Torma, H".(r116)
"Trefethen, N".(r246)
"Turkay M.".(r298)
"Turvey, R".(r184,r54)
"Vanderbei, R".(r207,r255)
"Vecchietti, A".(r296)
"Viswanathan, J".(r102)
"von Stryk, O".(r213)
"Voss, S".(r153)
"Wagner, H M".(r192,r165)
"Wall, T W".(r72)
"Westerlund, T".(r151)
"Wiegele A.".(r300)
"Wiens, T B".(r56)
"Williams, H P".(r14,r41)
"Wood, A J".(r176,r130,r131)
"World Bank".(r51,r57,r55)
"Wright, M H".(r79)
"Wright, S I".(r279)
"Yee, T F".(r97)
"Zenios, S A".(r177,r73)
"Zloof, M M".(r28)
/
set athr(ath,r) author reference mapping /
"Adhya, N".(r156,r239)
"Adjiman, C S".(r150)
"Aggarwal, A".(r100)
"Ahmad, M".(r134)
"Alatorre, J".(r16)
"Andersen, E".(r253)
"Anderson, D".(r184,r54)
"Anitescu, M".(r200)
"ARCNET".(r11)
"Aronofsky, J S".(r164)
"Ascher, U M".(r204)
"Audet, C".(r238)
"Averick, B M".(r203)
"Back, T".(r175)
"Balakrishnan, N".(r275)
"Balard, C L".(r117)
"Beasley, J E".(r263)
"Beauvais, J".(r92)
"Belotti, P".(r286)
"Beltramo, M A".(r53)
"Ben-Tal, A".(r237)
"Benson, H P".(r234)
"Bergendorff, H".(r60)
"Berna, T".(r129)
"Bertsekas, D P".(r293)
"Betts, J".(r208)
"Biegler, L T".(r202)
"Biggar, D R".(r322)
"Birge, J R".(r144)
"Blair, P D".(r319)
"Blitzer, C".(r47)
"Boehringer, C".(r112)
"Boger, G M".(r234)
"Bollapragada, S".(r227,r228)
"Bondarenko, A S".(r205)
"Borland".(r90)
"Borndoerfer, R".(r139)
"Bosch, R A".(r158,r254,r290)
"Boussofiane".(r140)
"Box, G E P".(r201)
"Boyd, S".(r320)
"Bracken, J".(r181,r18,r126,r26,r25,r24,r23,r22,r20,r19,r17,r21)
"Breton, M".(r259)
"Brimberg, J".(r238,r259)
"Brooke, A".(r67,r66)
"Brown, M".(r30)
"Bryson, A E".(r210,r209)
"Bulirsch, R".(r216,r211)
"Bureau T E".(r279)
"Burkard, R E".(r267)
"Bussieck, M R".(r160,r161,r228,r258,r260)
"Butzer, P L".(r226)
"C. Strugarek".(r304)
"Capriz, G".(r215)
"Carlson, R C".(r142)
"Carter, R G".(r203)
"Cattaneo, A".(r170)
"CDC".(r50,r10,r59)
"Cesari, L".(r199)
"Chakravarty, S".(r43)
"Chen, C H".(r273)
"Chenery, H B".(r178,r185,r187,r33,r173,r32)
"Cheng, H".(r227)
"Chlond, M J".(r248)
"Cho, B R".(r274)
"Choksi, A M".(r15)
"Chou, C Y".(r273)
"Choypeng, P".(r89)
"Cimatti, G".(r215)
"Claessens, M T".(r162)
"Clark, R H".(r288)
"Coello Coello, C A".(r148)
"Condon, T".(r76)
"Cox, D R".(r276)
"Cox, L H".(r283)
"Dahl, H".(r94,r76)
"Dammert, A".(r45,r30)
"Daniel, R C".(r248)
"Dantzig, G B".(r154,r180,r128,r9,r8,r7,r6,r5,r4,r3,r1,r125,r292)
"Day, R E".(r13)
"de Wetering, A V".(r224)
"de Wolf, D".(r157)
"Deaven, D M".(r197)
"Deb, K".(r147)
"den Hertog, D".(r247)
"Devarajan, S".(r76)
"di Tella, G".(r191)
"Dirkse, S P".(r240)
"Dolan, E D".(r194)
"Doufherty, D".(r269)
"Drud, A S".(r68,r67,r73)
"Dudeney, H E".(r220)
"Duloy, J H".(r83)
"Dutton, J M".(r164)
"Dyson".(r140)
"Edgar, T F".(r168)
"Eiger, G".(r237)
"El-Said, M".(r170)
"Elbers, A W".(r289)
"Eldersveld, S".(r208)
"Ellison, E F D".(r12)
"Erjavec, J".(r201)
"Ermoliev, Y".(r179)
"Esposito, W R".(r150)
"Fair, R C".(r69)
"Fasano, A".(r217)
"Feenstra, R".(r115)
"Ferris, M C".(r132,r240)
"Florios, K".(r294,r325)
"Floudas, C A".(r98,r100,r150,r251)
"Foulds, L R".(r236)
"Fourer, R".(r70,r36)
"Friedman, A".(r206)
"Fulkerson".(r154)
"Fullerton Don".(r117)
"GAMS Development Corporation".(r221,r222)
"GAMS Model Library".(r317)
"Garbiras, M".(r227)
"Gardner, M".(r225)
"Garver, L L".(r284)
"Gasawa, K".(r256)
"Gay, D M".(r70,r196)
"Gdanska, P".(r133)
"Gershovitz, V".(r237)
"Gill, P E".(r145)
"Gilmore, P C".(r265,r266)
"Glenshaw, P".(r60)
"Glowinski, R".(r214)
"Goemans M.X.".(r299)
"Golan, A".(r171)
"Gomory, R E".(r265,r266)
"Goreaux, L M".(r189)
"Goyal, M".(r147)
"Goyal, S K".(r230)
"Graham, R L".(r195)
"Greening, D".(r72)
"Groetschel, M".(r139)
"Grossmann, I E".(r103,r151,r97,r167,r102,r99,r95,r101,r96,r297,r298)
"Gueret, C".(r249)
"Guignard, M".(r219,r302)
"Gumus, Z H".(r150)
"Gunasekaran, A".(r230)
"Gunluk, O".(r321)
"Gutierrez, R A".(r229)
"H. Heitsch".(r304)
"Hallet, A J H".(r186)
"Hamada, K".(r314)
"Handbook of Test Problems".(r150)
"Hansen, P".(r238,r259)
"Hansen, T".(r106)
"Hanson, K".(r110)
"Harding, S T".(r150)
"Harjunkoski, I".(r193,r149)
"Harker, P T".(r108,r80,r241)
"Harrison, S".(r318)
"Hashimoto, H".(r256,r314)
"Haugland, D".(r236)
"Haverly, C A".(r155,r235)
"Heipcke, S".(r248)
"Hesamzadeh, M R".(r322)
"Hieu, P S".(r310)
"Hillier, F S".(r85)
"Himmelblau, D M".(r168,r183,r86,r35)
"Hitch, C J".(r190)
"Ho, K M".(r197)
"Ho, Y".(r209)
"Hock, W".(r250)
"Horowitz, J L".(r295)
"Hosoe, N".(r256,r314)
"House, B".(r127)
"Huffman, W".(r208)
"Hunter, W G".(r201)
"Husain, T".(r49)
"IBM".(r74)
"ILOG".(r291)
"IMSL Inc".(r58)
"Infanger, G".(r143)
"Inman, R".(r49)
"Itoh, H".(r315)
"Jain, V".(r167)
"Johnson".(r154)
"Jooste, A".(r323)
"Jornsten, K".(r236)
"Judge, G".(r171)
"Judge, G G".(r309)
"Juenger, M".(r270)
"Kall, P".(r137)
"Kallrath, J".(r252,r303,r306,r307)
"Kalvelagen, E".(r223)
"Kamiya, K".(r118)
"Karisch, S E".(r267)
"Kasnagoklu, H".(r81)
"Kehoe, T".(r119)
"Kelly, J P".(r283)
"Kendrick, D".(r66,r63,r31,r16,r37,r42,r39)
"Kennington, L".(r288)
"Kernighan, B W".(r70)
"Kilkenny, M".(r110)
"Kindleberger, C P".(r191)
"King, A J".(r136)
"Klepeis, J L".(r150)
"Klingman, D".(r287)
"Kocis, G R".(r103,r99,r95)
"Konno, H".(r231)
"Kotz, J".(r275)
"Kreuzer, P".(r161)
"Kucherenko, S".(r286)
"Kuijlaars, A".(r198)
"Kuno, T".(r231)
"Kutcher, G P".(r84,r82,r71,r134)
"Laguna, M".(r135)
"Lasdon, L S".(r168)
"Lawler, E L".(r163)
"Le, Q H".(r279)
"Le-Si, V".(r81)
"Lebret, H".(r320)
"Lenstra, J K".(r163)
"Lewis, J".(r38)
"Liberti, L".(r286)
"Lieberman, G J".(r85)
"Lih, K".(r259)
"Linderoth, J".(r262)
"Linderoth, J T".(r321)
"Lobo, M S".(r320)
"Locke, M".(r129)
"Loebel, A".(r139)
"Lopez de Silanes, F".(r113)
"Louveaux, F V".(r138,r144)
"Lu, Z".(r282)
"Macewan, A".(r33)
"MacGregor, J F".(r201)
"Mackinnon, J".(r124,r166)
"Maculan, N".(r286)
"Mallik, S".(r228)
"Mangasarian, O L".(r87)
"Manne, A S".(r104,r120,r109,r53,r188,r189,r34,r75,r52,r29)
"Maria, G".(r212)
"Markowitz, H M".(r188)
"Markusen, J R".(r115,r113)
"Martello, S".(r218)
"Martikainen T".(r230)
"Mathematica".(r243)
"Mattheij, R M M".(r204)
"Mavrotas, G".(r285,r325)
"McCormick, G P".(r181,r18,r126,r26,r25,r24,r23,r22,r20,r19,r17,r21)
"Meeraus, A".(r67,r94,r132,r66,r84,r60,r47,r31,r16,r15,r65,r30)
"Meeraus, W H".(r281)
"Melton, J W".(r46)
"Meneses, C N".(r282)
"Mennes, L B M".(r44)
"Meyer, C A".(r150)
"Meyer, R R".(r288)
"Michna, M".(r133)
"Miller, C E".(r305)
"Miller, D".(r171)
"Miller, M H".(r121)
"Miller, R E".(r319)
"Mitra, P".(r93,r12,r88)
"Mitsos, A".(r316)
"Mladenovic, N".(r238,r259)
"Moon, I".(r169)
"Morari, M".(r96)
"More, J J".(r203,r194)
"Morris, J R".(r197)
"Mulvey, J".(r73)
"Murphy, F H".(r107)
"Murray, W".(r145)
"Murtagh, B A".(r62)
"Napier, A".(r287)
"Nelson, C R".(r52)
"Nemhauser, G L".(r142)
"Nerz, E".(r211)
"Neumaier, A".(r264)
"Ni, H".(r258,r260)
"Norton, R D".(r40)
"O'Brochta, D".(r280)
"O'Mara, G T".(r84,r83)
"Ogura, A".(r272)
"Oliveira, C A S".(r282)
"Olubode-Awosola, O O".(r323,r324)
"Ortega, F".(r257)
"Palaniappan, S".(r45)
"Palmer, K H".(r64)
"Panton, D M".(r289)
"Pardalos, P M".(r150,r251,r282,r303,r307)
"Patil, R J".(r283)
"Paules IV, G E".(r98)
"Pereira, M V F".(r312,r313)
"Perroni, C".(r114)
"Pesch, H J".(r211)
"Petersen, C C".(r261)
"Petterson, F".(r151)
"Phan, S H".(r318)
"Phillips, M".(r227)
"Phillips, M D".(r274)
"Pindyck, R S".(r27)
"Pinter, J D".(r242,r244,r245)
"Pinto, L M V G".(r312,r313)
"Plateau M.C.".(r301)
"Pochet, Y".(r311)
"Porn, R".(r193)
"Preckel, P V".(r120)
"Primicerio, M".(r217)
"Prins, C".(r249)
"Puakpong, P".(r89)
"Raduchel, W J".(r32)
"Ragavan, R".(r174)
"Ramamurti, M".(r288)
"Raman, R".(r101,r297)
"Ramsey, F P".(r61)
"Rasmussen K.M.".(r317)
"Rebennack, S".(r303,r307)
"Reinelt, G".(r270)
"Rendl, F".(r267)
"Richels, R G".(r109)
"Rinnoy Kan, A H G".(r163)
"Robbins, A".(r269)
"Robinson, S".(r178,r38,r110,r170)
"Rohde, S M".(r174)
"Rosenborg, A".(r68)
"Rosenbrock, H H".(r78)
"Rosenthal, R E".(r89,r2)
"Rosenwein, M".(r219)
"Rothschild, B J".(r205)
"Rowse".(r166)
"Russell, R D".(r204)
"Rutherford, T F".(r132,r114,r113,r122,r116,r172,r112,r278)
"Saff, E B".(r198)
"Sahinidis, N".(r156,r229,r232,r239)
"Samuelson".(r166)
"Sandgren, E".(r152)
"Saunders, M A".(r145,r62)
"Savant, M".(r141)
"Scandizzo, P L".(r82,r40,r81)
"Scarf, H".(r123,r106)
"Schittkowski, K".(r250)
"Schoen, D J".(r279)
"Schrijver, A".(r159)
"Schweiger, C A".(r150)
"Serban, R".(r200)
"Sevaux, M".(r249)
"Sharov, A F".(r205)
"Shcherbina, O".(r264)
"Shepotylo, O".(r278)
"Sherali, H D".(r107)
"Shmoys, D B".(r163)
"Shoven, J".(r117,r105)
"Siddall, J N".(r146)
"Silver, E A".(r169)
"Skouras, S".(r294)
"Skrifvars, H".(r193)
"Sloane, N J A".(r271)
"Smeers, Y".(r157,r138,r65)
"Snell, E J".(r276)
"So, K C".(r52)
"Somwaru, A".(r268)
"Soyster, A L".(r107)
"Spencer, J E".(r121)
"Stehouwer, H P".(r247)
"Stinstra, E".(r247)
"Stoutjesdijk, A J".(r47,r44,r15,r30)
"Stutz, J".(r287)
"Suh, J S".(r48,r31)
"Syrquin, M".(r178,r182)
"Takayama, T".(r309)
"Tarr, D".(r278)
"Tawarmalani, M".(r156,r232,r239)
"Taylor, L".(r42)
"Tayyabkhan, M T".(r164)
"Teisberg, T J".(r77)
"Tendulkar, S".(r88)
"Thanassoulis".(r140)
"Thienel, S".(r270)
"Thoai, N V".(r233)
"Thompson, G".(r91)
"Thor, S".(r91)
"Thorpe, S".(r111)
"Tierney, L".(r277)
"Tjoa, I B".(r202)
"Toczek, J".(r308)
"Torma, H".(r116)
"Toth, P".(r218)
"Trefethen, N".(r246)
"Tsitsiklis, J N".(r293)
"Tucker, A W".(r305)
"Turkay M.".(r298)
"Turvey, R".(r184,r54)
"van Dijk, N M".(r162)
"van Schalkwyk H D".(r323)
"Vandenberghe, L".(r320)
"Vanderbei, R".(r207,r255)
"Vecchietti, A".(r296)
"Vestjens, A".(r247)
"Vietoriscz, T".(r29)
"Viswanathan, J".(r102)
"von Stryk, O".(r211,r213)
"von Thunen".(r166)
"Voss, S".(r153)
"W. Roemisch".(r304)
"Wagner, H M".(r192,r165)
"Wall, T W".(r72)
"Wallace, S W".(r137)
"Westerberg, A W".(r129)
"Westerlund, T".(r151,r193)
"Westphal, L E".(r173)
"Wets, R J".(r179)
"Weyant, J P".(r52)
"Whalley, J".(r117,r105)
"Wiegele A.".(r300)
"Wiens, T B".(r56)
"Williams, H P".(r14,r13,r41)
"Williamson, D P".(r299)
"Wolfe, P".(r292)
"Wollenberg, B F".(r176,r130,r131)
"Wolsey, L".(r257)
"Wolsey, L A".(r311)
"Wood, A J".(r176,r130,r131)
"Woodruff, D L".(r153)
"Woolsey, R E D".(r72)
"World Bank".(r51,r57,r55)
"Wright, M H".(r79)
"Wright, S I".(r279)
"Xue, G L".(r203)
"Yee, T F".(r97)
"Yli-Olli, P".(r230)
"Zemlin, R A".(r305)
"Zenios, S A".(r177,r94,r73)
"Zimmermann, U T".(r161)
"Zloof, M M".(r28)
"Zwaneveld, P J".(r162)
/
